# Generated by Django 5.0.2 on 2025-03-21 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMC_Entry_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentID', models.BigIntegerField(default=0)),
                ('AMC_Start_Date', models.DateField()),
                ('AMC_End_Date', models.DateField()),
                ('AMCMode', models.CharField(max_length=255)),
                ('YearExpense', models.BigIntegerField(blank=True, default=0, null=True)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('FC_Status', models.CharField(default='Pending', max_length=50)),
                ('FC_Action', models.CharField(max_length=50)),
                ('FC_ActionBy', models.BigIntegerField(blank=True, default=0, null=True)),
                ('FC_ActionDateTime', models.DateTimeField(blank=True, null=True)),
                ('GM_Status', models.CharField(default='Pending', max_length=50)),
                ('GM_Action', models.CharField(max_length=50)),
                ('GM_ActionBy', models.BigIntegerField(blank=True, default=0, null=True)),
                ('GM_ActionDateTime', models.DateTimeField(blank=True, null=True)),
                ('CEO_Status', models.CharField(default='Pending', max_length=50)),
                ('CEO_Action', models.CharField(max_length=50)),
                ('CEO_ActionBy', models.BigIntegerField(blank=True, default=0, null=True)),
                ('CEO_ActionDateTime', models.DateTimeField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('created_by', models.BigIntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_by', models.BigIntegerField(default=0)),
                ('modify_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
