# Generated by Django 5.0.2 on 2025-03-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amc_entry_master',
            old_name='AMCMode',
            new_name='AMCType',
        ),
        migrations.RenameField(
            model_name='amc_entry_master',
            old_name='YearExpense',
            new_name='AMC_Amount',
        ),
    ]
