# Generated by Django 5.0.2 on 2025-03-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0003_rename_status_amc_entry_master_final_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc_entry_master',
            name='Remarks',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
