# Generated by Django 5.0.2 on 2025-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0004_amc_entry_master_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc_entry_master',
            name='AMCType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amc_entry_master',
            name='Remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
