# Generated by Django 5.0.2 on 2025-04-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0006_medalliadata_reviewpro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedalliaData',
        ),
        migrations.DeleteModel(
            name='ReviewPro',
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='FileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
