# Generated by Django 5.0.2 on 2025-04-05 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0007_delete_medalliadata_delete_reviewpro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentID', models.BigIntegerField(default=0)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('MobileNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('SecondMobileNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('LandlineNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('State', models.CharField(blank=True, max_length=255, null=True)),
                ('Pincode', models.BigIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('created_by', models.BigIntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_by', models.BigIntegerField(default=0)),
                ('modify_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
