# Generated by Django 5.0.2 on 2025-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0008_vendordetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorDetails',
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorCity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorEmailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorLandlineNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorMobileNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorPincode',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorSecondMobileNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amc_entry_master',
            name='VendorState',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
