# Generated by Django 5.0.2 on 2025-06-18 07:46

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
       
        migrations.CreateModel(
            name='MedalliaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryDate', models.DateField(default=datetime.datetime(2025, 6, 18, 13, 15, 36, 198922))),
                ('PropertyName', models.CharField(max_length=255)),
                ('GuestName', models.CharField(max_length=255)),
                ('Month', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckInDate', models.DateField(blank=True, null=True)),
                ('CheckInProcess', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Cleanliness', models.CharField(blank=True, max_length=10, null=True)),
                ('ConditionOfHotel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('WohProgramExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('StaffHelpfulness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('RoomNo', models.IntegerField(blank=True, null=True)),
                ('ResponseDate', models.DateField(blank=True, null=True)),
                ('CheckOutDate', models.DateField(blank=True, null=True)),
                ('WorkingOrder', models.CharField(blank=True, max_length=10, null=True)),
                ('CustomerService', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('BreakfastExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('SpaExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('DeliveryHkServices', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('NPS', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('StaffResponsiveness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('WohAppExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OverallFnbExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PropertyAnticipatedGuestNeeds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('LpMemberSatisfaction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        
       
    ]
