# Generated by Django 5.0.2 on 2025-07-05 04:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestVoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryDate', models.DateField(default=django.utils.timezone.now)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=255)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryDate', models.DateField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('Reviewer', models.CharField(max_length=255)),
                ('Month', models.CharField(blank=True, max_length=255, null=True)),
                ('ReviewRating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Classification', models.CharField(blank=True, max_length=50, null=True)),
                ('Cleanliness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Location', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('LocationScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Room', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('RoomScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('GriTM', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PublishedDate', models.DateField()),
                ('RatingScale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Service', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('CleanlinessScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ValueScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Gastronomy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('GastronomyScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Source', models.CharField(blank=True, max_length=255, null=True)),
                ('ReviewScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ServiceScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('DepartmentRatingScale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ReviewTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('ReviewText', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='medalliadata',
            name='EntryDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771)),
        ),
        migrations.CreateModel(
            name='Entry_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 607771))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Entry_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestVoice.entry_master')),
                ('Item_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestVoice.item_master')),
            ],
        ),
    ]
