# Generated by Django 4.2.9 on 2024-05-06 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('SerialNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Make', models.CharField(blank=True, max_length=255, null=True)),
                ('Model_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Commissioning_Date', models.DateField(default=datetime.datetime(2024, 5, 6, 12, 7, 14, 929883))),
                ('Area', models.CharField(blank=True, max_length=255, null=True)),
                ('Warrantiy_Details', models.CharField(blank=True, max_length=255, null=True)),
                ('AMC_Details', models.CharField(blank=True, max_length=255, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('Documen_Attachment', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 6, 12, 7, 14, 929883))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 6, 12, 7, 14, 929883))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
