# Generated by Django 4.2.9 on 2024-05-07 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it_inventory',
            old_name='AMC_Details',
            new_name='AMC_Status',
        ),
        migrations.RenameField(
            model_name='it_inventory',
            old_name='Warrantiy_Details',
            new_name='Warrantiy_Status',
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='amc_yearly_expense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='amcend',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='amcstart',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='amctype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 11, 39, 34, 533581)),
        ),
    ]
