# Generated by Django 4.2.9 on 2024-05-08 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0002_rename_amc_details_it_inventory_amc_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcend',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcstart',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 26, 31, 956391)),
        ),
    ]
