# Generated by Django 4.2.9 on 2024-05-08 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0003_master_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 805318))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 805318))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcend',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcstart',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 804318)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 805318)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 3, 40, 805318)),
        ),
    ]
