# Generated by Django 4.2.9 on 2024-05-08 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0004_master_company_alter_it_inventory_commissioning_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 310415))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 310415))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcend',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcstart',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 309416)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 310415)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 54, 26, 310415)),
        ),
    ]
