# Generated by Django 4.2.9 on 2024-05-08 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0005_master_area_alter_it_inventory_commissioning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_inventory',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcend',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcstart',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 452379)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 454378)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 454378)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 453378)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 453378)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 453378)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 32, 2, 453378)),
        ),
    ]
