# Generated by Django 4.2.9 on 2024-05-08 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0006_it_inventory_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it_inventory',
            name='Documen_Attachment',
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='Quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='computer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='software_AMC_Start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='software_AMC_Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='software_AMC_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='software_AMC_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcend',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcstart',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 805064)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 805064)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 804065)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 805064)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 47, 2, 805064)),
        ),
    ]
