# Generated by Django 4.2.9 on 2024-05-10 07:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0007_remove_it_inventory_documen_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Software_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 215330))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 215330))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='it_inventory',
            old_name='email',
            new_name='Hardware_quantity',
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='Hardware_Per',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='Software_Quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='Software_unit_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='software_AMC_Yearly_Expense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='softwarename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='it_inventory',
            name='softwaretype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Commissioning_Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 213331)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 213331)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='Warrantiy_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='amcstart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 215330)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 215330)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 214331)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 214331)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 214331)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 33, 51, 214331)),
        ),
    ]
