# Generated by Django 4.2.9 on 2024-05-11 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0012_alter_it_inventory_createddatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it_inventory',
            old_name='Hardware_Per',
            new_name='hardware_AMC_Yearly_Expense',
        ),
        migrations.RenameField(
            model_name='it_inventory',
            old_name='Hardware_quantity',
            new_name='hardware_quantity',
        ),
        migrations.RenameField(
            model_name='it_inventory',
            old_name='amc_yearly_expense',
            new_name='hardware_unit_price',
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 165275)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 165275)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 167274)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 167274)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 166274)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 166274)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 166274)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 166274)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 167274)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 26, 17, 167274)),
        ),
    ]
