# Generated by Django 5.0.2 on 2024-09-11 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0017_alter_it_inventory_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 64735)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 64735)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 57, 39, 80465)),
        ),
    ]
