# Generated by Django 5.0.2 on 2025-05-17 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0020_alter_it_inventory_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 905374)),
        ),
    ]
