# Generated by Django 5.0.2 on 2025-06-02 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Inventory', '0021_alter_it_inventory_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_inventory',
            name='Inventory_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_area',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_category',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_company',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
        migrations.AlterField(
            model_name='master_software_type',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 12, 17, 34, 850168)),
        ),
    ]
