# Generated by Django 5.0.2 on 2025-05-19 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceSalaryForm',
            fields=[
                ('Application_Form_No', models.AutoField(primary_key=True, serialize=False)),
                ('EmpID', models.BigIntegerField(default=0)),
                ('EmployeeName', models.CharField(blank=True, max_length=255, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('DateofLoan', models.DateField(blank=True, null=True)),
                ('LoanAmount', models.BigIntegerField(default=0)),
                ('No_Of_Installments', models.BigIntegerField(default=0)),
                ('BankACNo', models.BigIntegerField(default=0)),
                ('Reasons_For_Request', models.CharField(blank=True, max_length=255, null=True)),
                ('Prev_Loan_Taken', models.BigIntegerField(default=0)),
                ('Dues_Repayment', models.BigIntegerField(default=0)),
                ('Prev_No_Of_Installments', models.BigIntegerField(default=0)),
                ('Reason_For_PreviousLoan', models.CharField(blank=True, max_length=255, null=True)),
                ('Current_Salary', models.CharField(blank=True, max_length=255, null=True)),
                ('Recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('DateofJoining', models.DateField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('created_by', models.BigIntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_by', models.BigIntegerField(default=0)),
                ('modify_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
