# Generated by Django 5.0.2 on 2025-05-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvanceSalaryForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalaryform',
            name='EmpID',
            field=models.CharField(max_length=200),
        ),
    ]
