# Generated by Django 5.0.2 on 2025-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvanceSalaryForm', '0002_alter_advancesalaryform_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesalaryform',
            name='emp_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
