# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('EmployeeCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Current_Salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Date_of_Last_salary_review', models.DateField()),
                ('Last_Increment_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Last_Increment_Slab_3', models.BooleanField(default=False)),
                ('Last_Increment_Slab_5', models.BooleanField(default=False)),
                ('Last_Increment_Slab_8', models.BooleanField(default=False)),
                ('Last_Increment_Slab_None', models.BooleanField(default=False)),
                ('Proposed_Salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Effective_Date', models.DateField()),
                ('Justification_Request', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
