# Generated by Django 5.0.6 on 2024-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clearance_From', '0003_clearenceemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearenceemp',
            name='FinishingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearenceemp',
            name='SeparationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
