# Generated by Django 5.0.6 on 2024-09-18 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clearance_From', '0005_clearanceitemdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturndataStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('ReceivedName', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ClearenceEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clearance_From.clearenceemp')),
                ('MasterClearanceItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clearance_From.masterreturnitem')),
            ],
        ),
    ]
