# Generated by Django 5.0.6 on 2024-09-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clearance_From', '0006_returnitemdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnitemdetail',
            old_name='MasterClearanceItem',
            new_name='MasterReturnItem',
        ),
    ]
