# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Confirm_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(blank=True, max_length=50, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Confirmation_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(blank=True, max_length=255, null=True)),
                ('EmpName', models.CharField(blank=True, max_length=255, null=True)),
                ('Position', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('JoiningDate', models.DateField()),
                ('ConfDate', models.DateField()),
                ('EmpConfirm', models.BooleanField(default=False)),
                ('Extended', models.CharField(blank=True, max_length=255, null=True)),
                ('Strengths', models.TextField(blank=True, null=True)),
                ('Improvement', models.TextField(blank=True, null=True)),
                ('Guidelines', models.BooleanField(default=False)),
                ('Trainingattended', models.TextField(blank=True, null=True)),
                ('LOC_ID', models.IntegerField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Confirmation_Objective_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectiveName', models.TextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Emp_Confirmation_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProbationConfirmation.emp_confirmation_master')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Confirmation_Objective_Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalName', models.TextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Emp_Confirmation_Objective_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProbationConfirmation.emp_confirmation_objective_details')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProbationConfirmation.category_master')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Confirmation_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsYes', models.BooleanField(default=False)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Emp_Confirmation_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProbationConfirmation.emp_confirmation_master')),
                ('Item_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProbationConfirmation.item_master')),
            ],
        ),
    ]
