# Generated by Django 5.0.2 on 2025-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProbationConfirmation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_confirmation_master',
            name='NetProConfirmID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
