# Generated by Django 5.0.2 on 2025-01-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProbationConfirmation', '0002_emp_confirmation_master_netproconfirmid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_confirmation_master',
            name='NetProConfirmID',
        ),
    ]
