# Generated by Django 5.0.2 on 2025-01-03 06:44

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JD_Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('Division', models.CharField(blank=True, max_length=255, null=True)),
                ('Position', models.CharField(blank=True, max_length=255, null=True)),
                ('Report_To', models.CharField(blank=True, max_length=255, null=True)),
                ('Level', models.CharField(blank=True, max_length=255, null=True)),
                ('Signatory', models.CharField(blank=True, max_length=255, null=True)),
                ('Effective_Date', models.DateField(default=django.utils.timezone.now)),
                ('JD_Approved_By', models.CharField(blank=True, max_length=255, null=True)),
                ('Job_Scope', ckeditor.fields.RichTextField()),
                ('Duties_Responsibilities', ckeditor.fields.RichTextField()),
                ('Job_Knowledge_Skills', ckeditor.fields.RichTextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Reference_No', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
