# Generated by Django 5.0.2 on 2025-12-04 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indemnity_Accommodation_Employee_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=250, null=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('generate_date', models.DateField(default=django.utils.timezone.now)),
                ('date_of_joining', models.DateField()),
                ('date_of_last_working', models.DateField()),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('Hr_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Hr_Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('HotelID', models.BigIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Indemnity_Accommodation_Deleted_File_Of_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('HotelID', models.BigIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Data_PrivacyExperience_Employee_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indemnity_Accommodation.indemnity_accommodation_employee_detail')),
            ],
        ),
    ]
