# Generated by Django 5.0.2 on 2026-01-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indemnity_Accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indemnity_accommodation_employee_detail',
            options={'ordering': ['id']},
        ),
    ]
