# Generated by Django 4.1.8 on 2023-11-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetterOfConfirmation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofconfirmationemployeedetail',
            name='emp_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
