# Generated by Django 5.0.2 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetterOfConfirmation', '0002_letterofconfirmationemployeedetail_emp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofconfirmationemployeedetail',
            name='data',
        ),
        migrations.RemoveField(
            model_name='letterofconfirmationemployeedetail',
            name='general_manager_name',
        ),
        migrations.AddField(
            model_name='letterofconfirmationemployeedetail',
            name='Issuing_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='letterofconfirmationemployeedetail',
            name='Issuing_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='prefix',
            field=models.CharField(max_length=50),
        ),
    ]
