# Generated by Django 5.0.2 on 2026-01-05 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetterOfConfirmation', '0004_alter_letterofconfirmation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofconfirmation',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmation',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationdeletedfileofemployee',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationdeletedfileofemployee',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='date_of_appointment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letterofconfirmationemployeedetail',
            name='date_of_confirmation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
