# Generated by Django 4.1.8 on 2024-02-14 11:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hotel', models.CharField(blank=True, max_length=100, null=True)),
                ('sources', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2024, 2, 14, 16, 34, 19, 947993))),
                ('gm_date', models.DateField(default=datetime.datetime(2024, 2, 14, 16, 34, 19, 947993))),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images')),
                ('room_no', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stay_days', models.PositiveIntegerField(blank=True, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('process_lapse', models.TextField(blank=True, null=True)),
                ('gm_comment', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('Action_Plan', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 2, 14, 16, 34, 19, 949068))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 2, 14, 16, 34, 19, 949068))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
