# Generated by Django 4.1.8 on 2024-02-14 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_departmentmaster_designationmaster'),
        ('Guest_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstay',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 16, 53, 21, 446847)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 16, 53, 21, 446847)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='OrganizationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 16, 53, 21, 446847)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='gm_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 16, 53, 21, 446847)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\Images\\GuestReview'),
        ),
    ]
