# Generated by Django 4.1.8 on 2024-02-14 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_departmentmaster_designationmaster'),
        ('Guest_reviews', '0002_alter_hotelstay_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstay',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 7, 54, 68160)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 7, 54, 68160)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='OrganizationID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 17, 7, 54, 68160)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='gm_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 17, 7, 54, 68160)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.organizationmaster'),
            preserve_default=False,
        ),
    ]
