# Generated by Django 5.0.2 on 2024-03-02 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_reviews', '0003_alter_hotelstay_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstay',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 12, 48, 49, 193546)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 12, 48, 49, 193546)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 12, 48, 49, 193546)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='gm_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 12, 48, 49, 193546)),
        ),
    ]
