# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_reviews', '0005_alter_hotelstay_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstay',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 876759)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 876759)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 876759)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='gm_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 876759)),
        ),
    ]
