# Generated by Django 5.0.2 on 2025-05-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_reviews', '0007_alter_hotelstay_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstay',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 292275)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 292275)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 292275)),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='gm_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 292275)),
        ),
    ]
