# Generated by Django 5.0.2 on 2026-01-05 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_reviews', '0010_alter_hotelstay_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstay',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='ModifyDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotelstay',
            name='gm_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
