# Generated by Django 4.1.8 on 2023-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedExpense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenseentrydetails',
            name='Isapplicable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('N/A', 'N/A')], default='Yes', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedexpenseentrydetails',
            name='Remakrs',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
