# Generated by Django 4.1.8 on 2023-08-26 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FixedExpense', '0002_fixedexpenseentrydetails_isapplicable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpenseDepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        # migrations.AddField(
        #     model_name='fixedexpensemaster',
        #     name='FixedExpenseDepartmentMaster',
        #     field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FixedExpense.fixedexpensedepartmentmaster'),
        #     preserve_default=False,
        # ),
    ]
