# Generated by Django 4.1.8 on 2023-08-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FixedExpense', '0003_fixedexpensedepartmentmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpensedepartmentmaster',
            name='sort_order',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedexpensemaster',
            name='FixedExpenseDepartmentMaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FixedExpense.fixedexpensedepartmentmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedexpensemaster',
            name='sort_order',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
