# Generated by Django 5.0.12 on 2025-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning_Letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='appeal',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='appeal_explained',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='associate_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='manager_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='verbalwarningmoduls',
            name='verbally_warned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
