# Generated by Django 5.0.12 on 2025-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning_Letters', '0002_alter_verbalwarningmoduls_appeal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='agree_warning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='appeal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='disagree_warning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='employee_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='employee_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='improvement_standard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='warning_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='witness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalwarningmodule',
            name='written_warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
