# Generated by Django 4.2.4 on 2023-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModRoasterCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modroastercalendar',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
