# Generated by Django 4.1.7 on 2023-03-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clearnce_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Separation_Date', models.DateField()),
                ('Position', models.CharField(max_length=100)),
                ('Finishing_Time', models.TimeField(blank=True)),
                ('Resignation_Letter', models.CharField(max_length=100)),
                ('Acc_Of_Resign', models.CharField(max_length=100)),
                ('Notice_Period_Served', models.CharField(max_length=100)),
                ('Notice_Period_Waived_Off', models.CharField(max_length=100)),
                ('Exit_Interview_By_Hr', models.CharField(max_length=100)),
                ('Full_And_Final_Settlement', models.CharField(max_length=100)),
            ],
        ),
    ]
