# Generated by Django 4.1.7 on 2023-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearnce_form',
            name='Acc_Of_Resign',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearnce_form',
            name='Exit_Interview_By_Hr',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearnce_form',
            name='Full_And_Final_Settlement',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearnce_form',
            name='Notice_Period_Served',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearnce_form',
            name='Notice_Period_Waived_Off',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearnce_form',
            name='Resignation_Letter',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50),
        ),
    ]
