# Generated by Django 4.1.7 on 2023-03-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0002_alter_clearnce_form_acc_of_resign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clerance_Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uniform_Returned', models.CharField(max_length=100)),
                ('LockerClear_LockerKey', models.CharField(max_length=100)),
                ('ID_InsuranceCard', models.CharField(max_length=100)),
                ('Name_Badge', models.CharField(max_length=100)),
                ('Employee_Handbook', models.CharField(max_length=100)),
                ('CUG_Sim_Card', models.CharField(max_length=100)),
                ('Cash_Floats', models.CharField(max_length=100)),
                ('Cash_Advance', models.CharField(max_length=100)),
                ('City_Ledger', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('Computer', models.CharField(max_length=100)),
                ('Email_Id_Locked', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Key_Returned', models.CharField(max_length=100)),
                ('Hotel_Keys', models.CharField(max_length=100)),
                ('Gate_Pass', models.CharField(max_length=100)),
            ],
        ),
    ]
