# Generated by Django 4.1.7 on 2023-03-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0003_clerance_item_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerance_item_master',
            old_name='CUG_Sim_Card',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='clerance_item_master',
            old_name='Cash_Advance',
            new_name='ItemTitle',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Cash_Floats',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='City_Ledger',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Computer',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Email_Id_Locked',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Employee_Handbook',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Gate_Pass',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Hotel_Keys',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='ID_InsuranceCard',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Key_Returned',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='LockerClear_LockerKey',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Material',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Name_Badge',
        ),
        migrations.RemoveField(
            model_name='clerance_item_master',
            name='Uniform_Returned',
        ),
    ]
