# Generated by Django 4.1.7 on 2023-03-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0004_rename_cug_sim_card_clerance_item_master_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerance_item_master',
            name='Department',
            field=models.CharField(choices=[('HR', 'HR'), ('Finance', 'Finance'), ('IT', 'IT'), ('House Keeping', 'House Keeping'), ('Security', 'Security'), ('Purchase', 'Purchase')], max_length=50),
        ),
        migrations.CreateModel(
            name='clearnce_formdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnedTo', models.CharField(max_length=100)),
                ('ReceivedBy', models.CharField(max_length=100)),
                ('Clerance_Item_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleranceform.clerance_item_master')),
                ('clearnce_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleranceform.clearnce_form')),
            ],
        ),
    ]
