# Generated by Django 4.1.7 on 2023-04-01 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0005_alter_clerance_item_master_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearnce_form',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clearnce_form',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clearnce_form',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clearnce_form',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clearnce_form',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
