# Generated by Django 4.1.7 on 2023-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0006_clearnce_form_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearnce_form',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
