# Generated by Django 4.1.8 on 2023-09-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0007_clearnce_form_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearnce_form',
            name='EmpCode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
