# Generated by Django 4.1.8 on 2023-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0008_clearnce_form_empcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearnce_form',
            name='Finishing_Time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
