# Generated by Django 4.1.8 on 2023-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleranceform', '0009_alter_clearnce_form_finishing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearnce_form',
            name='EmpCode',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
