# Generated by Django 5.0.6 on 2024-10-03 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist_Issued', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployeeChecklistMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Checklist', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ChecklistName',
        ),
    ]
