# Generated by Django 5.0.6 on 2024-10-04 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist_Issued', '0002_hremployeechecklistmaster_delete_checklistname'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployeeChecklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('Designtions', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
