# Generated by Django 5.0.6 on 2024-10-04 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist_Issued', '0004_hremployeechecklist_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployeeChecklist_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceivedStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('HREmployeeChecklistMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checklist_Issued.hremployeechecklistmaster')),
                ('HREmployeeChecklist_Entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checklist_Issued.hremployeechecklist_entry')),
            ],
        ),
    ]
