# Generated by Django 4.1.7 on 2023-04-11 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanty_Baggage_Register_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Room_No', models.CharField(max_length=100)),
                ('Guest_Name', models.CharField(max_length=100)),
                ('Arrival_Date', models.DateField(default=datetime.date.today)),
                ('Departure_Date', models.DateField(default=datetime.date.today)),
                ('Deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('Comment', models.TextField()),
                ('Front_Desk_Associate', models.CharField(max_length=100)),
                ('Duty_Manager', models.CharField(max_length=100)),
                ('Remarks', models.TextField()),
            ],
        ),
    ]
