# Generated by Django 4.1.7 on 2023-04-11 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scantybaggage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanty_baggage_register_form',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanty_baggage_register_form',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='scanty_baggage_register_form',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanty_baggage_register_form',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='scanty_baggage_register_form',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
