# Generated by Django 4.1.7 on 2023-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scantybaggage', '0002_scanty_baggage_register_form_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanty_baggage_register_form',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
