# Generated by Django 4.1.8 on 2024-02-09 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LetteofPromotion', '0003_alter_promotionletteremployeedetail_emp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleID', models.BigIntegerField(default=0)),
                ('Title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Monthly', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('Annum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('OrderBy', models.IntegerField(blank=True, default=0, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('PromotionLetterEmployeeDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetteofPromotion.promotionletteremployeedetail')),
            ],
        ),
    ]
