# Generated by Django 4.1.8 on 2024-02-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetteofPromotion', '0004_salarydetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarydetails',
            old_name='Annum',
            new_name='PresentSal',
        ),
        migrations.RenameField(
            model_name='salarydetails',
            old_name='Monthly',
            new_name='RevisedSal',
        ),
    ]
