# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
        ('LetteofPromotion', '0005_rename_annum_salarydetails_presentsal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionletteremployeedetail',
            name='data',
        ),
        migrations.RemoveField(
            model_name='promotionletteremployeedetail',
            name='general_manager_name',
        ),
        migrations.AddField(
            model_name='promotionletteremployeedetail',
            name='Issuing_designation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promotionletteremployeedetail',
            name='Issuing_manager_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promotionletteremployeedetail',
            name='PWI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotionletteremployeedetail',
            name='Promotiondepartment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='Promotiondesignation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='prefix',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PromotionSalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PresentSal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('RevisedSal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('PromotionLetterEmployeeDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetteofPromotion.promotionletteremployeedetail')),
                ('Salary_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.salarytitle_master')),
            ],
        ),
        migrations.DeleteModel(
            name='SalaryDetails',
        ),
    ]
