# Generated by Django 5.0.2 on 2025-01-14 09:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetteofPromotion', '0006_remove_promotionletteremployeedetail_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionletteremployeedetail',
            name='data',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionletteremployeedetail',
            name='general_manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='Issuing_designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='Issuing_manager_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='Promotiondepartment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='Promotiondesignation',
            field=models.CharField(max_length=100),
        ),
    ]
