# Generated by Django 5.0.2 on 2025-05-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetteofPromotion', '0007_promotionletteremployeedetail_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionletteremployeedetail',
            name='data',
        ),
        migrations.RemoveField(
            model_name='promotionletteremployeedetail',
            name='general_manager_name',
        ),
    ]
