# Generated by Django 4.1.7 on 2023-04-06 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM_Number', models.CharField(max_length=100)),
                ('PM_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Reason', models.TextField()),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
