# Generated by Django 4.1.7 on 2023-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_master',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
