# Generated by Django 4.1.8 on 2023-06-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpResigantionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Emp_Code', models.CharField(max_length=100)),
                ('DOJ', models.DateField(default=datetime.date.today)),
                ('Date_Of_res', models.DateField(default=datetime.date.today)),
                ('Dept', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('TypeofRes', models.CharField(choices=[('3 Months (fix as per designation)', '3 Months (fix as per designation)'), ('Negotiated notice period 2 months', 'Negotiated notice period 2 Months')], max_length=50)),
                ('NoticePeriod', models.CharField(choices=[('3 Months (fix as per designation)', '3 Months (fix as per designation)'), ('Negotiated notice period 2 months', 'Negotiated notice period 2 Months')], max_length=50)),
                ('Res_Reason', models.CharField(choices=[('Better salary', 'Better salary'), ('Better brand', 'Better brand'), ('Personal decision', 'Personal decision'), ('Better Opportunity', 'Better Opportunity'), ('Career Growth', 'Career Growth'), ('Due to family reason', 'Due to family reason'), ('Due to medical problem', 'Due to medical problem'), ('Other', 'Other')], max_length=50)),
                ('Ressubmittedto', models.CharField(max_length=50)),
                ('LastWorkingDays', models.DateField(default=datetime.date.today)),
                ('Res_acceptance_Date', models.DateField(default=datetime.date.today)),
                ('Res_acceptance_By', models.CharField(max_length=50)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
