# Generated by Django 4.1.8 on 2023-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='NoticePeriod',
            field=models.CharField(choices=[('3 Months (fix as per designation)', '3 Months (fix as per designation)'), ('Negotiated notice period 2 months', 'Negotiated notice period 2 Months')], max_length=150),
        ),
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='TypeofRes',
            field=models.CharField(choices=[('Email', 'Email'), ('Written', 'Written')], max_length=150),
        ),
    ]
