# Generated by Django 4.1.8 on 2023-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0002_alter_empresigantionmodel_noticeperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='Res_Reason',
            field=models.CharField(choices=[('Better salary', 'Better salary'), ('Better brand', 'Better brand'), ('Personal decision', 'Personal decision'), ('Better Opportunity', 'Better Opportunity'), ('Career Growth', 'Career Growth'), ('Due to family reason', 'Due to family reason'), ('Due to medical problem', 'Due to medical problem'), ('Other', 'Other')], max_length=150),
        ),
    ]
