# Generated by Django 4.1.8 on 2023-12-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0003_alter_empresigantionmodel_res_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='Designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
