# Generated by Django 5.0.2 on 2024-06-14 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0004_alter_empresigantionmodel_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisonHeadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=500, null=True)),
                ('FullName', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.CharField(blank=True, max_length=500, null=True)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='NoticePeriod',
            field=models.CharField(choices=[('3 Months (fix as per designation)', '3 Months (fix as per designation)'), ('Negotiated notice period 2 months', 'Negotiated notice period 2 Months'), ('Negotiated notice period 1 month', 'Negotiated notice period 1 Month'), ('Negotiated notice period 15 Days', 'Negotiated notice period 15 Days')], max_length=150),
        ),
    ]
