# Generated by Django 5.0.2 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0005_divisonheademail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='NoticePeriod',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='Res_Reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='empresigantionmodel',
            name='TypeofRes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
