# Generated by Django 5.0.11 on 2025-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0006_alter_empresigantionmodel_noticeperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresigantionmodel',
            name='LastEmpStatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
