# Generated by Django 5.0.11 on 2025-01-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0007_empresigantionmodel_lastempstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresigantionmodel',
            name='IsRevoke',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
