# Generated by Django 5.0.2 on 2025-05-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0008_empresigantionmodel_isrevoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresigantionmodel',
            name='IsRevoke',
        ),
    ]
