# Generated by Django 5.0.2 on 2025-11-24 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpResignation', '0009_remove_empresigantionmodel_isrevoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresigantionmodel',
            name='IsDEPT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='DEPTCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='DEPTCreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='FNB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='FNBCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='FNBCreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='Finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='FinanceCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='FinanceCreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HKCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HKCreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HRCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HRCreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='HotelID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='IT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='ITCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='ITCreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='IsRevoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresigantionmodel',
            name='Level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
