# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=255, null=True)),
                ('EmployeeCode', models.CharField(max_length=255, null=True)),
                ('DesignationGrade', models.CharField(max_length=255, null=True)),
                ('Department', models.CharField(max_length=255, null=True)),
                ('HrStatus', models.CharField(default='0', max_length=255, null=True)),
                ('HrComment', models.CharField(max_length=255, null=True)),
                ('ItStatus', models.CharField(default='0', max_length=255, null=True)),
                ('ItComment', models.CharField(max_length=255, null=True)),
                ('HodStatus', models.CharField(default='0', max_length=255, null=True)),
                ('HodComment', models.CharField(max_length=255, null=True)),
                ('ReportingtoDesigantion', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateofRequest', models.DateTimeField(null=True)),
                ('DateofIssue', models.DateTimeField(null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Type', models.CharField(max_length=255, null=True)),
                ('DomainType', models.CharField(max_length=255, null=True)),
                ('RequestedBy', models.CharField(max_length=255, null=True)),
                ('IsIssued', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ItInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT.itinformation')),
            ],
        ),
        migrations.CreateModel(
            name='MobileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateofRequest', models.DateTimeField(null=True)),
                ('DateofIssue', models.DateTimeField(null=True)),
                ('CompanyName', models.CharField(max_length=255, null=True)),
                ('ModelNumber', models.CharField(max_length=255, null=True)),
                ('IMEINumber', models.CharField(max_length=255, null=True)),
                ('Colour', models.CharField(max_length=255, null=True)),
                ('RequestedBy', models.CharField(max_length=255, null=True)),
                ('IsIssued', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ItInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT.itinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateofRequest', models.DateTimeField(null=True)),
                ('DateofIssue', models.DateTimeField(null=True)),
                ('MobileNo', models.CharField(max_length=255, null=True)),
                ('RequestedBy', models.CharField(max_length=255, null=True)),
                ('IsIssued', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ItInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT.itinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SystemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateofRequest', models.DateTimeField(null=True)),
                ('DateofIssue', models.DateTimeField(null=True)),
                ('SystemType', models.CharField(max_length=255, null=True)),
                ('CompanyName', models.CharField(max_length=255, null=True)),
                ('ModelNumber', models.CharField(max_length=255, null=True)),
                ('SerialNumber', models.CharField(max_length=255, null=True)),
                ('Configuration', models.TextField(blank=True, null=True)),
                ('RequestedBy', models.CharField(max_length=255, null=True)),
                ('IsIssued', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ItInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT.itinformation')),
            ],
        ),
    ]
