# Generated by Django 5.0.2 on 2025-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinformation',
            name='HotelOpsAccount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
