# Generated by Django 5.0.2 on 2025-11-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0002_itinformation_hotelopsaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildetail',
            name='IsReturn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobiledetail',
            name='IsReturn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simdetail',
            name='IsReturn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemdetail',
            name='IsReturn',
            field=models.BooleanField(default=False),
        ),
    ]
