# Generated by Django 5.0.2 on 2025-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0003_emaildetail_isreturn_mobiledetail_isreturn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildetail',
            old_name='IsReturn',
            new_name='IsReturned',
        ),
        migrations.RenameField(
            model_name='mobiledetail',
            old_name='IsReturn',
            new_name='IsReturned',
        ),
        migrations.RenameField(
            model_name='simdetail',
            old_name='IsReturn',
            new_name='IsReturned',
        ),
        migrations.RenameField(
            model_name='systemdetail',
            old_name='IsReturn',
            new_name='IsReturned',
        ),
        migrations.AddField(
            model_name='itinformation',
            name='IsClosed',
            field=models.BooleanField(default=False),
        ),
    ]
