# Generated by Django 5.0.2 on 2025-07-16 07:06

import ckeditor.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('NetProjectID', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('OpenPositionID', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('Department', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('AppliedDate', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('campaign_source', models.CharField(blank=True, max_length=255, null=True)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exportopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', ckeditor.fields.RichTextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departmetdata', models.CharField(blank=True, max_length=255, null=True)),
                ('levelsfor', models.CharField(blank=True, max_length=255, null=True)),
                ('Statusschedule', models.BooleanField(default=True)),
                ('Schedule_date', models.DateField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('college', 'College'), ('other', 'Other')], max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActionsResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedByUserID', models.BigIntegerField(default=0)),
                ('CreatedByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reason_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ca_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Open_position.careerresume')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.BigIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Open_position.notificationschedule')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('OpenDepartment', models.CharField(blank=True, max_length=255, null=True)),
                ('Job_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Salary', models.CharField(blank=True, max_length=255, null=True)),
                ('Locations', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Opened_On', models.DateField(blank=True, null=True)),
                ('Status', models.BooleanField(db_index=True, default=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedByUserID', models.BigIntegerField(default=0)),
                ('CreatedByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyByUserID', models.BigIntegerField(default=0)),
                ('ModifyByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('PositionImage', models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['Locations', 'Position', 'OpenDepartment'], name='Open_positi_Locatio_d1aa48_idx')],
            },
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='open_positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Open_position.openposition'),
        ),
    ]
