# Generated by Django 5.0.2 on 2025-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openposition',
            name='OpenLevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
