# Generated by Django 5.0.2 on 2025-09-16 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0002_openposition_openlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('College', models.CharField(blank=True, max_length=255, null=True)),
                ('School', models.CharField(blank=True, max_length=255, null=True)),
                ('Placement_Coordinator_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Placement_Coordinator_Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Placement_Coordinator_Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Department_Of_Reference', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
