# Generated by Django 5.0.2 on 2025-09-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0003_training_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_data',
            old_name='phone',
            new_name='CandidatePhone',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='Address',
            new_name='Candidate_Address',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='Department_Of_Reference',
            new_name='Department_Of_Preference',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='middle_name',
            new_name='Middle_Name',
        ),
        migrations.RemoveField(
            model_name='training_data',
            name='School',
        ),
    ]
