# Generated by Django 5.0.2 on 2025-09-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0004_rename_phone_training_data_candidatephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_data',
            name='Is_Training_Data',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
