# Generated by Django 5.0.2 on 2025-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0005_training_data_is_training_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_data',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='training_data',
            old_name='CandidatePhone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='training_data',
            name='campaign_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training_data',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
