# Generated by Django 5.0.2 on 2025-09-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0006_rename_first_name_training_data_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_data',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
