# Generated by Django 5.0.2 on 2025-09-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0007_training_data_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_data',
            old_name='Email',
            new_name='email',
        ),
    ]
