# Generated by Django 5.0.2 on 2025-09-17 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0008_rename_email_training_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_data',
            name='AppliedDate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
