# Generated by Django 5.0.2 on 2025-09-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0009_training_data_applieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
