# Generated by Django 5.0.2 on 2025-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0010_alter_training_data_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_data',
            name='AppliedDate',
        ),
        migrations.RemoveField(
            model_name='training_data',
            name='campaign_source',
        ),
        migrations.RemoveField(
            model_name='training_data',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='training_data',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Candidate_Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='College',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Department_Of_Preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Is_Training_Data',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Middle_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Placement_Coordinator_Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Placement_Coordinator_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='Placement_Coordinator_Phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Resume_Profile/'),
        ),
    ]
