# Generated by Django 5.0.2 on 2025-09-17 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0011_remove_training_data_applieddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerresume',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='ModifyDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='careerresume',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
