# Generated by Django 5.0.2 on 2025-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0012_careerresume_createdby_careerresume_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerresume',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='careerresume',
            name='Is_Training_Data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
