# Generated by Django 5.0.2 on 2025-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0013_careerresume_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training_Data',
        ),
        migrations.AddField(
            model_name='openposition',
            name='OpenDivision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
