# Generated by Django 5.0.2 on 2025-11-26 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_position', '0014_delete_training_data_openposition_opendivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerresume',
            name='CreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='careerresume',
            name='CreatedDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='careerresume',
            name='Is_Training_Data',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='careerresume',
            name='ModifyBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='careerresume',
            name='ModifyDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='careerresume',
            name='OrganizationID',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
