# Generated by Django 5.0.2 on 2025-01-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAssessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentlevelconfig',
            name='HeadDepartment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departmentlevelconfigdetails',
            name='DepartmentLevelConfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InterviewAssessment.departmentlevelconfig'),
        ),
    ]
