# Generated by Django 5.0.11 on 2025-01-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAssessment', '0002_departmentlevelconfig_headdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_master',
            name='ceo_UserID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment_master',
            name='gm_UserID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment_master',
            name='hod_UserID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment_master',
            name='hr_UserID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment_master',
            name='rd_UserID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
