# Generated by Django 5.0.2 on 2026-01-05 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAssessment', '0003_assessment_master_ceo_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_master',
            name='LastLoistatusModifyDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
