# Generated by Django 4.1.7 on 2023-04-05 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Equipment_Name', models.CharField(max_length=100)),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Model_No', models.IntegerField()),
                ('In_Working_Condition', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Last_Servicing_Date', models.DateField(default=datetime.date.today)),
                ('AMC_Covered', models.CharField(max_length=100)),
                ('Serial_No', models.IntegerField()),
                ('Remarks', models.TextField()),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
