# Generated by Django 4.1.7 on 2023-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_inventory',
            name='AMC_Covered',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
    ]
