# Generated by Django 4.1.7 on 2023-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentinventory', '0002_alter_equipment_inventory_amc_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_inventory',
            name='Model_No',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment_inventory',
            name='Serial_No',
            field=models.CharField(max_length=100),
        ),
    ]
