# Generated by Django 4.1.7 on 2023-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentinventory', '0003_alter_equipment_inventory_model_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_inventory',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
