# Generated by Django 4.1.7 on 2023-04-03 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake_Order_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('From', models.CharField(max_length=100)),
                ('Time', models.TimeField(max_length=20)),
                ('Guest_Name', models.CharField(max_length=100)),
                ('To_Be_Prepared_For', models.CharField(max_length=100)),
                ('Size', models.CharField(max_length=100)),
                ('Type_Of_Cake', models.CharField(max_length=100)),
                ('Required_Date', models.DateField()),
                ('Required_Time', models.TimeField(max_length=20)),
                ('Packing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Selling_Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Message_On_Cake', models.CharField(max_length=100)),
                ('Complimentory', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Authorised_By', models.CharField(max_length=100)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
