# Generated by Django 4.1.7 on 2023-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_order_form',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
