# Generated by Django 4.1.7 on 2023-04-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grooming_Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Audit_Type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Shoes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Shocks', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Nails', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Hair', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Uniform', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Name_Badge', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Brand_Pin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Remarks', models.TextField()),
            ],
        ),
    ]
