# Generated by Django 4.1.7 on 2023-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomingregisteration', '0002_grooming_registeration_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grooming_registeration',
            name='Audit_Type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=50),
        ),
    ]
