# Generated by Django 4.1.7 on 2023-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomingregisteration', '0003_alter_grooming_registeration_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grooming_registeration',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
