# Generated by Django 4.1.7 on 2023-04-04 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('In_Time', models.TimeField()),
                ('Name', models.CharField(max_length=100)),
                ('Purpose_Of_Visite', models.TextField()),
            ],
        ),
    ]
