# Generated by Django 4.1.7 on 2023-04-04 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_pass',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor_pass',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='visitor_pass',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor_pass',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='visitor_pass',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
