# Generated by Django 4.1.7 on 2023-04-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorpass', '0002_visitor_pass_createdby_visitor_pass_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_pass',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
