# Generated by Django 5.0.2 on 2025-11-03 06:49

import ckeditor.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HumanResources', '0016_alter_salary_details_effective_effectivefrom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LETTEROFINTENTEmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=50)),
                ('InterviewID', models.CharField(max_length=50)),
                ('date_of_intent', models.DateField(default=datetime.date.today)),
                ('date_of_joining', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('ctc', models.IntegerField()),
                ('address', models.TextField()),
                ('Issuing_manager_name', models.CharField(max_length=255)),
                ('Issuing_designation', models.CharField(max_length=255)),
                ('Reporting_Manager', models.CharField(max_length=255)),
                ('visible_salary_breakup', models.CharField(max_length=10)),
                ('visible_ctc', models.CharField(max_length=10)),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ReIssue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LETTEROFINTENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', ckeditor.fields.RichTextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LETTEROFINTENTDeletedFileofEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('LETTEROFINTENTEmployeeDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Letterofintent.letterofintentemployeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permonth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Perannum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('LETTEROFINTENTEmployeeDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Letterofintent.letterofintentemployeedetail')),
                ('Salary_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.salarytitle_master')),
            ],
        ),
    ]
