# Generated by Django 5.0.2 on 2025-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letterofintent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofintentemployeedetail',
            name='Reporting_Manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
