# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewProgram', '0002_alter_front_of_house_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_of_house',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 888831)),
        ),
        migrations.AlterField(
            model_name='front_of_house',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 888831)),
        ),
        migrations.AlterField(
            model_name='front_of_house',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 888831)),
        ),
    ]
