# Generated by Django 5.0.2 on 2025-01-14 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewProgram', '0003_alter_front_of_house_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_of_house',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 588436)),
        ),
        migrations.AlterField(
            model_name='front_of_house',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 588436)),
        ),
        migrations.AlterField(
            model_name='front_of_house',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 588436)),
        ),
    ]
