# Generated by Django 4.1.7 on 2023-04-17 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHlpReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Category', models.CharField(choices=[('Water', 'Water'), ('Water Storage', 'Water Storage'), ('Water Consumption', 'Water Consumption'), ('Electricity', 'Electricity'), ('Diesel Consumed', 'Diesel Consumed')], max_length=50)),
            ],
        ),
    ]
