# Generated by Django 4.1.7 on 2023-04-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Govt_Electricity_Board', models.CharField(max_length=100)),
                ('DG_Runing_Hour', models.CharField(max_length=100)),
                ('Diesel_Consumed', models.CharField(max_length=100)),
                ('DG1', models.CharField(max_length=100)),
                ('DG2', models.CharField(max_length=100)),
                ('DG3', models.CharField(max_length=100)),
                ('Stem_Boiler1', models.CharField(max_length=100)),
                ('Stem_Boiler2', models.CharField(max_length=100)),
                ('Hot_Water_Generator1', models.CharField(max_length=100)),
                ('Hot_Water_Generator2', models.CharField(max_length=100)),
                ('LPG_PNG_Cons', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Water_Received_From_Gov', models.CharField(max_length=100)),
                ('Tanker_Water_Received', models.CharField(max_length=100)),
                ('Rate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Water_Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soft_Water', models.CharField(max_length=100)),
                ('RO_Water', models.CharField(max_length=100)),
                ('Flusing', models.CharField(max_length=100)),
                ('Irrigation', models.CharField(max_length=100)),
                ('Swimming_Pool', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Water_Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fire_Water_Tank', models.CharField(max_length=100)),
                ('Raw_Water_Tank', models.CharField(max_length=100)),
                ('Treated_Water_Tank', models.CharField(max_length=100)),
            ],
        ),
    ]
