# Generated by Django 4.1.7 on 2023-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0002_electricity_water_water_consumption_water_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diesel_Consumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DG1', models.CharField(max_length=100)),
                ('DG2', models.CharField(max_length=100)),
                ('DG3', models.CharField(max_length=100)),
                ('Stem_Boiler1', models.CharField(max_length=100)),
                ('Stem_Boiler2', models.CharField(max_length=100)),
                ('Hot_Water_Generator1', models.CharField(max_length=100)),
                ('Hot_Water_Generator2', models.CharField(max_length=100)),
                ('LPG_PNG_Cons', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='Diesel_Consumed',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='Hot_Water_Generator1',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='Hot_Water_Generator2',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='LPG_PNG_Cons',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='Stem_Boiler1',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='Stem_Boiler2',
        ),
    ]
