# Generated by Django 4.1.7 on 2023-04-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0003_diesel_consumed_remove_electricity_diesel_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel_consumed',
            name='DailyHlpReportForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.dailyhlpreportform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricity',
            name='DailyHlpReportForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.dailyhlpreportform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='DailyHlpReportForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.dailyhlpreportform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water_consumption',
            name='DailyHlpReportForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.dailyhlpreportform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water_storage',
            name='DailyHlpReportForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.dailyhlpreportform'),
            preserve_default=False,
        ),
    ]
