# Generated by Django 4.1.7 on 2023-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0004_diesel_consumed_dailyhlpreportform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='DailyHlpReportForm',
        ),
        migrations.RemoveField(
            model_name='water',
            name='DailyHlpReportForm',
        ),
        migrations.RemoveField(
            model_name='water_consumption',
            name='DailyHlpReportForm',
        ),
        migrations.RemoveField(
            model_name='water_storage',
            name='DailyHlpReportForm',
        ),
        migrations.RemoveField(
            model_name='dailyhlpreportform',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Diesel_Consumed',
        ),
        migrations.DeleteModel(
            name='Electricity',
        ),
        migrations.DeleteModel(
            name='Water',
        ),
        migrations.DeleteModel(
            name='Water_Consumption',
        ),
        migrations.DeleteModel(
            name='Water_Storage',
        ),
    ]
