# Generated by Django 4.1.7 on 2023-04-18 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0005_category_remove_electricity_dailyhlpreportform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhlpreportform',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyhlpreportform',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dailyhlpreportform',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyhlpreportform',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dailyhlpreportform',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
