# Generated by Django 4.1.7 on 2023-04-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0006_dailyhlpreportform_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Item_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Year', models.CharField(max_length=100)),
                ('Last_Year', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.category')),
                ('Dailyhlpreportform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DailyHlpReport.dailyhlpreportform')),
            ],
        ),
    ]
