# Generated by Django 4.1.7 on 2023-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0007_category_item_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_Item_Master',
        ),
        migrations.RenameField(
            model_name='category_item_detail',
            old_name='Category',
            new_name='Category_Item_Master',
        ),
    ]
