# Generated by Django 4.1.7 on 2023-04-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyHlpReport', '0008_rename_category_category_item_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_item_detail',
            old_name='Amount',
            new_name='ItemTitle',
        ),
        migrations.RemoveField(
            model_name='category_item_detail',
            name='Current_Year',
        ),
        migrations.RemoveField(
            model_name='category_item_detail',
            name='Dailyhlpreportform',
        ),
        migrations.RemoveField(
            model_name='category_item_detail',
            name='Last_Year',
        ),
    ]
