# Generated by Django 5.0.2 on 2025-11-28 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Inventory_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.BigIntegerField(blank=True, default=0, null=True)),
                ('EmployeeName', models.CharField(max_length=255, null=True)),
                ('EmployeeCode', models.CharField(max_length=255, null=True)),
                ('DesignationGrade', models.CharField(max_length=255, null=True)),
                ('Department', models.CharField(max_length=255, null=True)),
                ('HrStatus', models.CharField(default='0', max_length=255, null=True)),
                ('HrComment', models.CharField(max_length=255, null=True)),
                ('HousekeppingStatus', models.CharField(default='0', max_length=255, null=True)),
                ('HousekeppingComment', models.CharField(max_length=255, null=True)),
                ('HodStatus', models.CharField(default='0', max_length=255, null=True)),
                ('HodComment', models.CharField(max_length=255, null=True)),
                ('ReportingtoDesigantion', models.CharField(max_length=255)),
                ('Return', models.BooleanField(default=False)),
                ('ReturnAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('HR', models.BooleanField(default=False)),
                ('HRCreatedBy', models.BigIntegerField(default=0)),
                ('IssuedDate', models.DateField(default=django.utils.timezone.now)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HR_Inventory_Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=255, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Year', models.IntegerField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HR_Inventory_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewQuantity', models.IntegerField(blank=True, null=True)),
                ('AlteredQuantity', models.IntegerField(blank=True, null=True)),
                ('IssuedQuantity', models.IntegerField(blank=True, null=True)),
                ('ReturnNewQuantity', models.IntegerField(blank=True, null=True)),
                ('ReturnAlteredQuantity', models.IntegerField(blank=True, null=True)),
                ('ReturnIssuedQuantity', models.IntegerField(blank=True, null=True)),
                ('NewVariance', models.IntegerField(blank=True, null=True)),
                ('AlterVariance', models.IntegerField(blank=True, null=True)),
                ('IssueVariance', models.IntegerField(blank=True, null=True)),
                ('TotalCharged', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
                ('UniformInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_Inventory.hr_inventory_information')),
                ('UniformItemMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_Inventory.hr_inventory_item_master')),
            ],
        ),
    ]
