# Generated by Django 5.0.2 on 2025-11-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr_inventory_details',
            old_name='UniformInformation',
            new_name='HR_Inventory_Information',
        ),
        migrations.RenameField(
            model_name='hr_inventory_details',
            old_name='UniformItemMaster',
            new_name='HR_Inventory_Item_Master',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='AlterVariance',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='AlteredQuantity',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='IssueVariance',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='IssuedQuantity',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='NewQuantity',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='NewVariance',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='ReturnAlteredQuantity',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='ReturnIssuedQuantity',
        ),
        migrations.RemoveField(
            model_name='hr_inventory_details',
            name='ReturnNewQuantity',
        ),
        migrations.AddField(
            model_name='hr_inventory_details',
            name='Item_Issued',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hr_inventory_details',
            name='Item_Returned',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
