# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Standard', models.TextField()),
                ('Type', models.CharField(max_length=255)),
                ('SortOrder', models.BigIntegerField(default=999)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KraEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmittedByName', models.CharField(blank=True, max_length=255, null=True)),
                ('SubmittedByEmployeeCode', models.CharField(blank=True, max_length=255, null=True)),
                ('SubmittedByDesignation', models.CharField(blank=True, max_length=255, null=True)),
                ('SubmittedYear', models.IntegerField(blank=True, null=True)),
                ('SubmittedMonth', models.IntegerField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TargetAssignMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignByName', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignByEmployeeCode', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignByDesignation', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignToName', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignToEmployeeCode', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignToDesignation', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignYear', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('CreatedByUserName', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignDate', models.DateField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TargetAssignMasterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('AssignMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRA.targetassignmaster')),
                ('KRA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRA.kra')),
            ],
        ),
        migrations.CreateModel(
            name='KraEntryMasterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actual', models.CharField(blank=True, max_length=255, null=True)),
                ('ActualValue', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('KraEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRA.kraentrymaster')),
                ('TargetAssignMasterDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRA.targetassignmasterdetails')),
            ],
        ),
    ]
