# Generated by Django 5.0.12 on 2025-05-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kra',
            name='ComparisonType',
            field=models.CharField(choices=[('higher', 'Higher is better'), ('lower', 'Lower is better'), ('equal', 'Exact match')], default='higher', max_length=10),
        ),
        migrations.AddField(
            model_name='kra',
            name='Defination',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kra',
            name='Source',
            field=models.CharField(default='Entry', max_length=255),
            preserve_default=False,
        ),
    ]
