# Generated by Django 5.0.12 on 2025-05-21 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0002_kra_comparisontype_kra_defination_kra_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelKRAStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('KRAID', models.BigIntegerField(default=0)),
                ('StandardValue', models.CharField(max_length=255)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
