# Generated by Django 5.0.12 on 2025-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0003_hotelkrastandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetassignmaster',
            name='AssignMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetassignmaster',
            name='AssignToMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetassignmaster',
            name='AssignToYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
