# Generated by Django 5.0.2 on 2025-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0004_targetassignmaster_assignmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kraentrymaster',
            name='IsFinalSubmit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kraentrymaster',
            name='IsSave',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
