# Generated by Django 5.0.2 on 2025-07-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0005_kraentrymaster_isfinalsubmit_kraentrymaster_issave'),
    ]

    operations = [
        migrations.AddField(
            model_name='kra',
            name='Select_Value_Type',
            field=models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('decimal', 'Decimal'), ('text', 'Text')], default='Number', max_length=10),
        ),
    ]
