# Generated by Django 5.0.2 on 2025-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0006_kra_select_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelkrastandard',
            name='CompareWithValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelkrastandard',
            name='StandardValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
