# Generated by Django 5.0.2 on 2025-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0007_hotelkrastandard_comparewithvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kra',
            name='Standard',
            field=models.TextField(blank=True, null=True),
        ),
    ]
