# Generated by Django 5.0.2 on 2025-07-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0008_alter_kra_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kra',
            name='Select_Value_Type',
            field=models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('decimal', 'Decimal'), ('text', 'Text')], default='number', max_length=10),
        ),
    ]
