# Generated by Django 5.0.2 on 2025-07-15 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0009_alter_kra_select_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetassignmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='targetassignmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
