# Generated by Django 5.0.2 on 2025-07-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0011_alter_hotelkrastandard_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetassignmaster',
            name='AssignToDoj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
