# Generated by Django 5.0.2 on 2025-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0012_targetassignmaster_assigntodoj'),
    ]

    operations = [
        migrations.AddField(
            model_name='kraentrymasterdetails',
            name='KRAID',
            field=models.BigIntegerField(default=0),
        ),
    ]
