# Generated by Django 5.0.2 on 2025-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0013_kraentrymasterdetails_kraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kraentrymasterdetails',
            name='StandardValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
