# Generated by Django 5.0.2 on 2026-01-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0014_kraentrymasterdetails_standardvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='kra',
            name='IsApplicable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
