# Generated by Django 5.0.2 on 2026-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRA', '0015_kra_isapplicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kra',
            name='IsApplicable',
        ),
        migrations.AddField(
            model_name='hotelkrastandard',
            name='IsApplicable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
