# Generated by Django 4.1.7 on 2023-04-19 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_Registration_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=100)),
                ('From', models.DateField(default=datetime.date.today)),
                ('To', models.DateField(default=datetime.date.today)),
                ('Referee_Company_Name', models.CharField(max_length=100)),
                ('Final_Position', models.CharField(max_length=100)),
                ('Refeere_Name', models.CharField(max_length=100)),
                ('Did_You_Directly_Supervise', models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50)),
                ('Refeere_Position', models.CharField(max_length=100)),
                ('Refeere_Phone_No', models.CharField(max_length=100)),
            ],
        ),
    ]
