# Generated by Django 4.1.7 on 2023-04-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_registration_form',
            name='Strength',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='Weaknesses',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
