# Generated by Django 4.1.7 on 2023-04-20 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0002_reference_registration_form_strength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_registration_form',
            old_name='Strength',
            new_name='Checked_By',
        ),
        migrations.RemoveField(
            model_name='reference_registration_form',
            name='Weaknesses',
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='Would_You_ReHire_This_Person',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
