# Generated by Django 4.1.7 on 2023-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0003_rename_strength_reference_registration_form_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_registration_form',
            name='Development_Areas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='Reason_For_Leaving',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='Strenght',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='Weaknesses',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='What_Would_His_Peers_Say_About_Him',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='What_Would_His_Supervisor_Say_About_Him',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='What_is_Best_Way_To_Manage_This_Candidate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
