# Generated by Django 4.1.7 on 2023-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0004_reference_registration_form_development_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Preference_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preference_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
