# Generated by Django 4.1.7 on 2023-04-20 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0005_job_preference_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_registration_form',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reference_registration_form',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
