# Generated by Django 4.1.7 on 2023-04-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0006_reference_registration_form_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_registration_form',
            name='Overall_Performance',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
