# Generated by Django 4.1.7 on 2023-04-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0007_reference_registration_form_overall_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_formdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habits', models.CharField(max_length=100)),
                ('Job_Preference_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReferenceCheck.job_preference_master')),
                ('Reference_Registration_Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReferenceCheck.reference_registration_form')),
            ],
        ),
    ]
