# Generated by Django 4.1.7 on 2023-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0008_reference_formdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_registration_form',
            name='Overall_Performance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference_registration_form',
            name='Strenght',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference_registration_form',
            name='Weaknesses',
            field=models.TextField(),
        ),
    ]
