# Generated by Django 4.1.7 on 2023-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceCheck', '0009_alter_reference_registration_form_overall_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_registration_form',
            name='Development_Areas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference_registration_form',
            name='Reason_For_Leaving',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference_registration_form',
            name='What_Would_His_Peers_Say_About_Him',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference_registration_form',
            name='What_Would_His_Supervisor_Say_About_Him',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference_registration_form',
            name='What_is_Best_Way_To_Manage_This_Candidate',
            field=models.TextField(),
        ),
    ]
