# Generated by Django 4.1.7 on 2023-05-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='EntryMonth',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='EntryYear',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pl_engineering_master',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
