# Generated by Django 4.1.7 on 2023-05-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0002_alter_pl_engineering_entry_master_entrymonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_engineering_entrydetails',
            name='PL_Engineering_Entry_Master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.pl_engineering_entry_master'),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entrydetails',
            name='PL_Engineering_Master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.pl_engineering_master'),
        ),
    ]
