# Generated by Django 4.1.7 on 2023-05-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0003_alter_pl_engineering_entrydetails_pl_engineering_entry_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_engineering_entrydetails',
            name='PL_Engineering_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
