# Generated by Django 4.1.7 on 2023-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0004_alter_pl_engineering_entrydetails_pl_engineering_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='SalaryAndWages',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
