# Generated by Django 4.1.7 on 2023-05-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0005_alter_pl_engineering_entry_master_salaryandwages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_engineering_entrydetails',
            name='PL_Engineering_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
