# Generated by Django 4.1.8 on 2023-07-21 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0006_alter_pl_engineering_entrydetails_pl_engineering_amount'),
    ]

    operations = [
        
    
       
    ]
