# Generated by Django 4.1.7 on 2023-06-07 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0009_plutilitiesentrymaster_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pl_engineering_entry_master',
            name='TraneeStaff',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SM_SalesEntryMarketingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SM_Sales_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('SM_MarketingMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.sm_marketingmaster')),
                ('SM_SalesEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.sm_salesentrymaster')),
            ],
        ),
        migrations.CreateModel(
            name='SM_SalesEntryExpenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SM_Sales_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('SM_SalesEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.sm_salesentrymaster')),
                ('SM_SalesExpenseMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.sm_salesexpensemaster')),
            ],
        ),
    ]
