# Generated by Django 4.1.7 on 2023-06-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0010_pl_engineering_entry_master_traneestaff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pl_engineering_entry_master',
            old_name='TraneeStaff',
            new_name='TraineeStaff',
        ),
    ]
