# Generated by Django 4.1.7 on 2023-06-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0011_rename_traneestaff_pl_engineering_entry_master_traineestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='pl_engineering_entry_master',
            name='PayrollAndRelatedExpenses',
            field=models.BigIntegerField(default=0),
        ),
    ]
