# Generated by Django 4.1.7 on 2023-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0012_pl_engineering_entry_master_payrollandrelatedexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='Bonuses_and_Incentives',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='EmployeeBenefits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='PayrollAndRelatedExpenses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='PayrollRelatedExpenses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='SalaryAndWages',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='Salary_Wages_and_Bonuses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='TotalExpenses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ag_securityentrymaster',
            name='Total_Other_Expenses',
            field=models.BigIntegerField(default=0),
        ),
    ]
