# Generated by Django 4.1.7 on 2023-06-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0013_ag_securityentrymaster_bonuses_and_incentives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ag_securityentrymaster',
            name='Salary_Wages_and_Bonuses',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
