# Generated by Django 4.1.7 on 2023-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0016_ag_hrentrymaster_bonuses_and_incentives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='Bonuses_and_Incentives',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='EmployeeBenefits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='PayrollAndRelatedExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='PayrollRelatedExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='SalaryAndWages',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='Salary_Wages_and_Bonuses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='TotalExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ag_hrentrymaster',
            name='Total_Other_Expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
