# Generated by Django 4.1.7 on 2023-06-08 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0017_alter_ag_hrentrymaster_bonuses_and_incentives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_AG_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Total_AGEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Bonuses_and_Incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_Other_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Total_AGEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Total_AGEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.total_agentrymaster')),
                ('Total_AG_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.total_ag_master')),
            ],
        ),
    ]
