# Generated by Django 4.1.7 on 2023-06-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0019_sm_salemarketingentrymaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sm_marketingentrydetails',
            old_name='SM_Marketing_Amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='sm_salesentrydetails',
            old_name='SM_Sales_Amount',
            new_name='Amount',
        ),
    ]
