# Generated by Django 4.1.7 on 2023-06-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0020_rename_sm_marketing_amount_sm_marketingentrydetails_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sm_marketingentrydetails',
            old_name='Amount',
            new_name='AmountMarketing',
        ),
        migrations.RenameField(
            model_name='sm_salesentrydetails',
            old_name='Amount',
            new_name='AmountSales',
        ),
    ]
