# Generated by Django 4.1.7 on 2023-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0021_rename_amount_sm_marketingentrydetails_amountmarketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sm_marketingexpensemaster',
            old_name='title',
            new_name='Mtitle',
        ),
    ]
