# Generated by Django 4.1.7 on 2023-06-12 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0024_ag_analysis_master_ag_analysisentrymaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ag_ratioanalysis_master',
            old_name='title_1',
            new_name='title_2',
        ),
        migrations.AddField(
            model_name='ag_analysisentrymaster',
            name='Bonuses_and_Incentives',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ag_analysisentrymaster',
            name='SalaryAndWages',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='AG_AnalysisEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('AG_AnalysisEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.ag_analysisentrymaster')),
                ('AG_Analysis_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.ag_analysis_master')),
            ],
        ),
    ]
