# Generated by Django 4.1.7 on 2023-06-13 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0029_ood_healthentrymaster_ood_healthmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FB_BanquetEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('FoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalFoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalBEVERAGEREVENUE', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('HallRental', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_RevenueMisc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalOtherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FoodCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfFBSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualEquipmentCostOfSale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_OtherCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOf_OtherRev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GrossProfit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Bonuses_and_Incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_Other_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('DepartmentIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FB_BanquetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FB_BanquetEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('FB_BanquetEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.fb_banquetentrymaster')),
                ('FB_BanquetMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.fb_banquetmaster')),
            ],
        ),
    ]
