# Generated by Django 4.1.7 on 2023-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0035_pl_roomsentrymaster_pl_roomsmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='Bonuses_and_Incentives',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='EmployeeBenefits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='PL_Engineering_Related_Expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='PayrollAndRelatedExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='SalaryAndWages',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='Salary_Wages_and_Bonuses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='TotalExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='Total_Other_Expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pl_engineering_entry_master',
            name='TraineeStaff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
