# Generated by Django 4.1.7 on 2023-06-20 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0038_pl_summaryentrymaster_pl_summarymaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_FBEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('FoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalFoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalBeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualEquipmentCostOfSales1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_OtherCostOfSales1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('HallRental', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue_MISC', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalOtherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FoodCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageCostOfSales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfFBSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualEquipmentCostOfSales2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_OtherCostOfSales2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfOtherRev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GrossProfit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Total_FBMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Total_FBEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Total_FBEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.total_fbentrymaster')),
                ('Total_FBMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.total_fbmaster')),
            ],
        ),
    ]
