# Generated by Django 4.1.7 on 2023-06-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0039_total_fbentrymaster_total_fbmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='AveBeveragePerCoverage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='AveFoodAndBeveragePerCoverage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='AveFoodPerCoverage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='DepartmentIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='NoOfBeverageCovers',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='NoOfFoodCovers',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='NumberOfGuests',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='Occupany',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='RoomsAvailable',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='RoomsOccupied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='Total_Other_Expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
