# Generated by Django 4.1.7 on 2023-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0040_total_fbentrymaster_avebeveragepercoverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='Bonuses_and_Incentives',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='total_fbentrymaster',
            name='SalaryAndWages',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
