# Generated by Django 4.2.4 on 2023-12-19 06:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media_Asset_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Media', models.FileField(upload_to='media_asset_library')),
                ('Thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='media_asset_library/thumbnails')),
                ('Media_Type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=20)),
                ('Descriptions', models.TextField()),
                ('Upload_Date', models.DateField(default=datetime.date.today)),
                ('Expiration_Date', models.DateField()),
                ('Upload_By', models.CharField(max_length=200)),
                ('For_Hotels', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('Original_Width', models.PositiveIntegerField(default=0)),
                ('Original_Height', models.PositiveIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media_Asset_Library_App.categories')),
            ],
        ),
    ]
