# Generated by Django 4.2.4 on 2023-12-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Asset_Library_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_asset_library',
            name='Thumbnail',
        ),
    ]
