# Generated by Django 4.2.4 on 2023-12-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Asset_Library_App', '0002_remove_media_asset_library_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_asset_library',
            name='Thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media_asset_library/thumbnails'),
        ),
    ]
