# Generated by Django 5.0.1 on 2024-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_Asset_Library_App', '0004_auto_20231220_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='media_asset_library',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
