# Generated by Django 4.1.7 on 2023-03-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform_Inventory_Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField()),
                ('To', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Uniform_Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100)),
                ('Fresh', models.CharField(max_length=100)),
                ('Soiled', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
            ],
        ),
    ]
