# Generated by Django 4.1.7 on 2023-03-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforminventorysheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniform_item_master',
            old_name='Fresh',
            new_name='Item_Title_Name',
        ),
        migrations.RemoveField(
            model_name='uniform_item_master',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='uniform_item_master',
            name='Soiled',
        ),
        migrations.RemoveField(
            model_name='uniform_item_master',
            name='Total',
        ),
        migrations.CreateModel(
            name='Uniform_Item_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fresh', models.CharField(max_length=100)),
                ('Soiled', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
                ('Uniform_Inventory_Sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforminventorysheet.uniform_inventory_sheet')),
                ('Uniform_Item_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforminventorysheet.uniform_item_master')),
            ],
        ),
    ]
