# Generated by Django 4.1.7 on 2023-04-01 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforminventorysheet', '0002_rename_fresh_uniform_item_master_item_title_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_inventory_sheet',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniform_inventory_sheet',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='uniform_inventory_sheet',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniform_inventory_sheet',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='uniform_inventory_sheet',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
