# Generated by Django 4.1.7 on 2023-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforminventorysheet', '0003_uniform_inventory_sheet_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_inventory_sheet',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
