# Generated by Django 4.1.8 on 2023-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforminventorysheet', '0004_uniform_inventory_sheet_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_item_master',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
