"""
Django settings for hotelopsmgmtpy project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
import django

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yail7&d2+8^)n2^6fhh0bwnw-cb1dh1iq=tfgx4ln$-kr1xk95'
FERNET_KEY = 'fW_hGbCB_TCL5XyRby4lVBgKJrm21G4bHX2Xxz6ElwY='
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
X_FRAME_OPTIONS = 'ALLOW-FROM http://hotelops.in'

CSP_FRAME_ANCESTORS = [
    "'self'",  # Allow from the same origin
    "http://hotelops.in",  # Allow from your .NET project
    "https://*.careersatnile.com",
    "http://hrm.hotelops.in",
    "https://hrm.hotelops.in",
    "http://hrm.hopr.in",
    "https://hrm.hopr.in"
]


CSRF_COOKIE_DOMAIN = ['.hopr.in','localhost']


# settings.py
CSRF_TRUSTED_ORIGINS = [
    "http://hrm.hotelops.in",
    "https://hrm.hotelops.in",   # include https if you also serve via HTTPS
    "http://hrm.hopr.in",
    "https://hrm.hopr.in"
]

CORS_ALLOW_ALL_ORIGINS = True
# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # 'django.contrib.humanize',
    # 'indian_numbers',
    'cakeorder',
    # 'django_rename_app',
    'app',
    
    'widget_tweaks',
    'casualmanpower',
    'waterconsumption',
    'cleranceform',
    'uniforminventorysheet',
    'masterlineninventory',
    'master',
    'FullandFinalSettlement',
    'SAConfig',
    'EmpResignation',
    'EmpTermination',
    'EmpAbsconding',
    'FixedExpense',
    # 'SalesWeeklyReview',
    # 'HBudgetReport',
    'PreOpeningDoc',
    'HotelBudget',
    'TrainingAssessment',
    'HrEvent',
    'ModRoasterCalendar',
    'SalesEventCalendar',
    'LETTER_OF_WORK_EXPERIENCE',
    'ckeditor',
    'LetteofPromotion',
    'LETTEROFAPPOINTMENT',
    'LetterOfConfirmation',
    'Letterofintent',
    'LetterSalaryIncrement',
    'EmailReader',
    'YearlyBudget',
    'Leave_Management_System',
    'Guest_reviews',
    'Hiring_Reporting_Performance_Review_Guidelines',
    'Agreement',
    'NewProgram',
    'Employee_Payroll',
    'Project_Approvel_Templates',
    'pacer',
    'IT_Inventory','review','dashboard','InterviewAssessment',
  'HumanResources',
  'Reference_check',
  'ProbationConfirmation',
  'EmailNotification',
  'IT',
  'PADP',
  'UniformInventory',
  'Salary_Correction',
  'Manning_Guide',
   'Job_Description',
   'Open_position',
   'ExitInterview',
   'Warning_Letters',
   'Clearance_From',
   'Checklist_Issued',
'PublicAccess',
  'KRA',
   'CodeOfConduct',

   'RevealingLetter',
   'GuestVoice',
   'AMC_Renewal',
   'AdvanceSalaryForm',
   'Travel_Details',
   'Salary_Structure',
   'User_Rights_Module',
   'Upload_Resume',
   'Ranking_Board',
   'HR_Inventory',
#    'Employee_Personal_Dashboard',
#    'HR_Dashboard',

   'rest_framework',
   'django_filters',
#    'django_crontab',
]



SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # or use cache or file-based

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
   
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'hotelopsmgmtpy.urls'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotelopsmgmtpy.wsgi.application'
# settings.py — HTTP / testing (temporary only)
ALLOWED_HOSTS = ['hrm.hotelops.in', 'localhost', '127.0.0.1','hrm.hopr.in']

# If using plain HTTP for now, include this origin for CSRF checks
CSRF_TRUSTED_ORIGINS = ['http://hrm.hotelops.in','http://hrm.hopr.in','https://hrm.hopr.in']

# Cookie settings for HTTP (NOT secure; only for testing)
SESSION_COOKIE_DOMAIN = '.hotelops.in'   # or '.hotelops.in' if sharing across subdomains
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SECURE = False               # allow cookie over HTTP (temp)
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'             # keeps normal behavior

# You can keep SECURE_PROXY_SSL_HEADER but it's not needed for pure HTTP
SECURE_PROXY_SSL_HEADER = True
USE_X_FORWARDED_HOST = True


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    #     'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'cake_order',
    #     'USER': 'root',
    #     'PASSWORD': 'Admin123456789',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # }
    "default": {
        "ENGINE": "mssql",
        "NAME": "hotelopsmgmtpydb",
        "USER": "sa",
        "PASSWORD": "Nsc@992475000",
        "HOST": "UPNW2K1902",  
    },
    'OPTIONS': {
    'driver': 'ODBC Driver 17 for SQL Server',  # or 18
}
}
# Use the database for session storage
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Ensure the following settings are correct for session cookies



# Set session cookie age to 30 days (2592000 seconds)
#SESSION_COOKIE_AGE = 2592000  # 30 days in seconds

# Optional: Set session to expire at browser close if True
#SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Optional: Enable session security for HTTPS
#SESSION_COOKIE_SECURE = True 

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

# TIME_ZONE = 'UTC'



USE_I18N = True

USE_TZ = True
DATE_FORMAT = "d-b-y"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'

STATIC_URL = 'static/'
CORS_ORIGIN_WHITELIST = (
  'http://localhost:8000',
  'http://localhost:50970',
  "https://*.hotelops.in",
  "https://hotelops.in",
  "http://*.hotelops.in",
  "http://hotelops.in",
  "https://*.careersatnile.com",
  "http://hrm.hotelops.in",
   "https://hrm.hotelops.in"
  
)
# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')




MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 
 
if not os.path.exists(MEDIA_ROOT):
    try:
        os.makedirs(MEDIA_ROOT)
        print(f"Created media folder: {MEDIA_ROOT}")
    except OSError as e:
        print(f"Error creating media folder: {e}")

        
#STATIC_URL = 'static/'
 
# Add these new lines
#STATICFILES_DIRS = (
#   os.path.join(BASE_DIR, 'static'),
#)
 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@hotelops.in'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'vishal@7990'  # Your Gmail password or app password
