"""
Django settings for hotelopsmgmtpy project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
import django
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yail7&d2+8^)n2^6fhh0bwnw-cb1dh1iq=tfgx4ln$-kr1xk95'
FERNET_KEY = 'fW_hGbCB_TCL5XyRby4lVBgKJrm21G4bHX2Xxz6ElwY='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

  
ALLOWED_HOSTS = ["hotelops.in","localhost","127.0.0.1","http://localhost:50970"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # 'django.contrib.humanize',
    # 'indian_numbers',
    'cakeorder',
    # 'django_rename_app',
    'app',
    
    'widget_tweaks',
    'casualmanpower',
    'waterconsumption',
    'cleranceform',
    'uniforminventorysheet',
    'masterlineninventory',
    'master',
    'FullandFinalSettlement',
    'SAConfig',
    'EmpResignation',
    'EmpTermination',
    'EmpAbsconding',
    'FixedExpense',
    # 'SalesWeeklyReview',
    # 'HBudgetReport',
    'PreOpeningDoc',
    'HotelBudget',
    'TrainingAssessment',
    'HrEvent',
    'ModRoasterCalendar',
    'SalesEventCalendar',
    'LETTER_OF_WORK_EXPERIENCE',
    'LetteofPromotion',
    'LETTEROFAPPOINTMENT',
    'LetterOfConfirmation',
    'Letterofintent',
    'LetterSalaryIncrement',
    'EmailReader',
    'YearlyBudget',
    'Leave_Management_System',
    'Guest_reviews',
    'Hiring_Reporting_Performance_Review_Guidelines',
    'Agreement',
    'NewProgram',
    'Employee_Payroll',
    'Project_Approvel_Templates',
    'pacer',
    'IT_Inventory','review','dashboard','InterviewAssessment',
  'HumanResources',
  'Reference_check',
  'ProbationConfirmation',
  'EmailNotification',
  'IT',
  'PADP',
  'UniformInventory',
  'Salary_Correction',
  'Manning_Guide',
   'Job_Description',
   'Open_position',
   'ExitInterview',
   'Warning_Letters',
   'Clearance_From',
   'Checklist_Issued',
'PublicAccess',
  'KRA',
   'CodeOfConduct',

   'RevealingLetter',
   'GuestVoice',
   'AMC_Renewal',
   'AdvanceSalaryForm',
   'Travel_Details',
   'Salary_Structure',
   'User_Rights_Module',
   'Upload_Resume',
   'Ranking_Board',
   'HR_Inventory',
   'Letter_Of_Trainees_Experience',
   'Policy_Data_Privacy',
   'Debit_Note',
   'Policy_Posh',
   'Indemnity_Accommodation',
    # 'django_ckeditor_5',
    # 'ckeditor_uploader',
    # 'Employee_Personal_Dashboard',
    # 'HR_Dashboard',
   'ckeditor',
   'rest_framework',
   'django_filters',
#    'django_crontab',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
   # "http://localhost:50970",
    # Add other allowed origins if needed
#]
X_FRAME_OPTIONS = 'http://localhost:50970' 
CORS_ORIGIN_WHITELIST = (
  'http://localhost:8000',
  'http://localhost:50970',
  "https://*.hotelops.in"
)
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
    
]

ROOT_URLCONF = 'hotelopsmgmtpy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotelopsmgmtpy.wsgi.application'
# DATE_INPUT_FORMATS = [
#     '%d/%b/%Y'
# ]
# USE_I18N = True
# USE_L10N = False # Here 
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# Use the database for session storage
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Set session cookie age to 30 days (2592000 seconds)
SESSION_COOKIE_AGE = 2592000  # 30 days in seconds

# Optional: Set session to expire at browser close if True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Optional: Enable session security for HTTPS
SESSION_COOKIE_SECURE = True 

DATABASES = {
    # Live Conntection String code ----->
    "default": {
        "ENGINE": "mssql",
        "NAME": "hotelopsmgmtpydb",
        "USER": "HopsDevDarpan",
        "PASSWORD": "Nile@#$Udaipur@#$2050",
        # "HOST": "hotelopsvm",  
        "HOST": "tcp:20.204.50.57,1433",  
    },

    # Lo`cal Conntection String code ----->
    # "default": {
    #     "ENGINE": "mssql",
    #     "NAME": "HOPSPYAPI",
    #     "USER": "sa",
    #     "PASSWORD": "NileUdaipur@#20182040",
    #     # "HOST": "HotelOpsVM",  
    #     "HOST": "HOTELOPS_PY02",  
    # },

    # Local Conntection String code -----> working
    # "default": {
    #     "ENGINE": "mssql",
    #     "NAME": "hotelopsmgmtpydb",
    #     "USER": "sa",
    #     "PASSWORD": "NileUdaipur@#20182040",
    #     # "HOST": "HotelOpsVM",  
    #     "HOST": "HOTELOPS_PY02",  
    # },
    
    # https://hrm.hopr.in/Dashboard/
    
    # "default": {
    #     "ENGINE": "mssql",
    #     "NAME": "hotelopsmgmtpydb",
    #     "USER": "sa",
    #     "PASSWORD": "Nsc@992475000",
    #     "HOST": "115.245.57.133",
    #     "PORT": "6981", 
    #     # "PORT": "6981",  # remove if SQL Server is local/default instance 
    #     "OPTIONS": {
    #         "driver": "ODBC Driver 17 for SQL Server",
    #     },
    # },
    
    # Local Conntection String code -----> working
    # "default": {
    #     "ENGINE": "mssql",
    #     "NAME": "hotelopsmgmtpydbVasu",
    #     "USER": "HOPSDEV",
    #     "PASSWORD": "Nile@#$Udaipur@#$2050",
    #     # "PORT": "6981",  
    #     "HOST": "115.245.57.133",
    #     "PORT": "6981",
    # },
}



# LANGUAGE_CODE = 'hi-in'

# TIME_ZONE = 'UTC'

# USE_I18N = False

# USE_L10N = True
# USE_THOUSAND_SEPARATOR = True

# USE_TZ = True

# LANGUAGE_CODE = 'en-IN'
# USE_I18N = False
# USE_L10N = True
# USE_THOUSAND_SEPARATOR = True
# NUMBER_GROUPING = (2, 2, 0)
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

# TIME_ZONE = 'UTC'



USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'

STATIC_URL = 'static/'

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 

if not os.path.exists(MEDIA_ROOT):
    try:
        os.makedirs(MEDIA_ROOT)
        print(f"Created media folder: {MEDIA_ROOT}")
    except OSError as e:
        print(f"Error creating media folder: {e}")
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS  = 25000

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@hotelops.in'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'vishal@7990'  # Your Gmail password or app password



# CRONJOBS = [
#     ('14 17* * *', 'django.core.management.call_command', ['send_reminders']),
#     # ('0 9 * * *', 'django.core.management.call_command', ['send_reminders']),
# ]
# Ensure the cron job is set up to run daily at 9 AM


WKHTMLTOPDF_CMD = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"


