# Generated by Django 4.1.7 on 2023-07-05 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HvarianceReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PL_Engineering_Entry_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(blank=True, default=0)),
                ('EntryYear', models.BigIntegerField(blank=True, default=0)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Bonuses_and_Incentives', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TraineeStaff', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PL_Engineering_Related_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_Other_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PL_Engineering_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PL_Engineering_EntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PL_Engineering_Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('PL_Engineering_Entry_Master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HvarianceReport.pl_engineering_entry_master')),
                ('PL_Engineering_Master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HvarianceReport.pl_engineering_master')),
            ],
        ),
    ]
