# Generated by Django 4.1.7 on 2023-07-05 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HvarianceReport', '0010_ood_laundryentrymaster_ood_laundrymaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OOD_TransportEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('ExternalGuestTransportation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GuestTransportRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Cost_OfGuestTransportation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_CostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Gross_Profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Bonuses_and_Incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_Other_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('DepartmentIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OOD_TransportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OOD_TransportEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('OOD_TransportEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HvarianceReport.ood_transportentrymaster')),
                ('OOD_TransportMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HvarianceReport.ood_transportmaster')),
            ],
        ),
    ]
