# Generated by Django 4.1.7 on 2023-07-06 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HvarianceReport', '0020_outlet_5entrymaster_outlet_5master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_FBEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('FoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalFoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalBeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualEquipmentCostOfSales1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_OtherCostOfSales1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('HallRental', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue_MISC', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalOtherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FoodCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageCostOfSales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfFBSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualEquipmentCostOfSales2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_OtherCostOfSales2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfOtherRev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GrossProfit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Bonuses_and_Incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_Other_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('DepartmentIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('RoomsAvailable', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('RoomsOccupied', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Occupany', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('NumberOfGuests', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('NoOfFoodCovers', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('NoOfBeverageCovers', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AveFoodPerCoverage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AveBeveragePerCoverage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AveFoodAndBeveragePerCoverage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Total_FBMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Total_FBEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Total_FBEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HvarianceReport.total_fbentrymaster')),
                ('Total_FBMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HvarianceReport.total_fbmaster')),
            ],
        ),
    ]
