# Generated by Django 5.0.2 on 2024-10-14 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAccessUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueToken', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ModelName', models.CharField(max_length=255)),
                ('AppName', models.CharField(max_length=255)),
                ('InstanceId', models.CharField(max_length=255)),
            ],
        ),
    ]
