# Generated by Django 5.0.2 on 2024-10-14 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccessurl',
            name='ExpiryDatetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 12, 2, 58, 448448, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='publicaccessurl',
            name='IsClicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicaccessurl',
            name='LastClicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
