# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAccess', '0003_alter_publicaccessurl_expirydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccessurl',
            name='ExpiryDatetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 6, 44, 43, 378826, tzinfo=datetime.timezone.utc)),
        ),
    ]
