# Generated by Django 5.0.2 on 2025-01-14 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAccess', '0004_alter_publicaccessurl_expirydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccessurl',
            name='ExpiryDatetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 9, 39, 53, 397807, tzinfo=datetime.timezone.utc)),
        ),
    ]
