# Generated by Django 5.0.2 on 2025-05-17 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAccess', '0006_alter_publicaccessurl_expirydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccessurl',
            name='ExpiryDatetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 10, 34, 57, 175367, tzinfo=datetime.timezone.utc)),
        ),
    ]
