# Generated by Django 5.0.2 on 2025-07-05 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAccess', '0007_alter_publicaccessurl_expirydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccessurl',
            name='ExpiryDatetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 4, 41, 25, 592087, tzinfo=datetime.timezone.utc)),
        ),
    ]
