# Generated by Django 5.0.2 on 2026-01-05 10:39

import PublicAccess.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAccess', '0008_alter_publicaccessurl_expirydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccessurl',
            name='ExpiryDatetime',
            field=models.DateTimeField(default=PublicAccess.models.default_expiry),
        ),
    ]
