# Generated by Django 5.0.2 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTER_OF_WORK_EXPERIENCE', '0002_alter_letterofexperienceemployeedetail_emp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofexperienceemployeedetail',
            name='Hr_manager_name',
        ),
        migrations.RemoveField(
            model_name='letterofexperienceemployeedetail',
            name='data',
        ),
        migrations.AddField(
            model_name='letterofexperienceemployeedetail',
            name='Hr_Designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='letterofexperienceemployeedetail',
            name='Hr_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='letterofexperienceemployeedetail',
            name='prefix',
            field=models.CharField(max_length=20),
        ),
    ]
