# Generated by Django 4.1.8 on 2024-01-12 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Type_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Is_Active', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 381547))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 381547))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Leave_Process_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Status', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 383547))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 383547))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Type_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Leave_Process_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 383547))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 383547))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Process_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_process_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Leave_Config_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monitor_Balance', models.BooleanField(default=False)),
                ('Carry_FWD', models.BooleanField(default=False)),
                ('Encash', models.BooleanField(default=False)),
                ('Financial_Year_Start_Date', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 382550))),
                ('Financial_Year_End_Date', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 382550))),
                ('Appn_Times', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Apply_Max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Apply_Min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Overdaft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Maximum_Accumulation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('YearlyLeave', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IsMonthly', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 382550))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 382550))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Type_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_Date', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 386548))),
                ('Emp_code', models.CharField(max_length=255)),
                ('Start_Date', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 387547))),
                ('From_1st_Half', models.BooleanField(default=False)),
                ('From_2nd_Half', models.BooleanField(default=False)),
                ('End_Date', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 387547))),
                ('To_1st_Half', models.BooleanField(default=False)),
                ('To_2nd_Half', models.BooleanField(default=False)),
                ('Reason', models.TextField()),
                ('Status', models.IntegerField()),
                ('Total_credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 387547))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 387547))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Type_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmpMonthLevelDebitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 386548))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 386548))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Type_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmpMonthLevelCreditMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=255)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 385551))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 385551))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Type_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Emp_Leave_Balance_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=255)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 384548))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 33, 42, 384548))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Leave_Type_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
