# Generated by Django 5.0.1 on 2024-01-16 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0002_leave_application_leaveappliedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 608427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 608427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 608427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 608427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 609427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 609427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 610426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='End_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 610426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 609427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 610426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Start_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 610426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 606430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='Financial_Year_End_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 606430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='Financial_Year_Start_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 606430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 606430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 607428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 607428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 607428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 607428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 605429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 45, 57, 605429, tzinfo=datetime.timezone.utc)),
        ),
    ]
