# Generated by Django 4.1.8 on 2024-01-16 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0005_alter_emp_leave_balance_master_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 868157)),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 868157)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 869176)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 869176)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 869176)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 869176)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 870168)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='End_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 870168)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 870168)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 870168)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Start_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 870168)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 865563)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='Financial_Year_End_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 865563)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='Financial_Year_Start_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 865563)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 865563)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 867610)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 867610)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 866826)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 866826)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 863884)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 42, 16, 863884)),
        ),
    ]
