# Generated by Django 4.1.8 on 2024-02-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0008_alter_emp_leave_balance_master_createddatetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='National_Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628))),
                ('Description', models.TextField()),
                ('Is_Active', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Optional_Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628))),
                ('Description', models.TextField()),
                ('Is_Active', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 964640)),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 964640)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 964640)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 964640)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 964640)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 964640)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 965639)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='End_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 965639)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 965639)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 965639)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Start_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 965639)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='Financial_Year_End_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='Financial_Year_Start_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962628)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 963640)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 963640)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 963640)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 963640)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962113)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 18, 33, 59, 962113)),
        ),
    ]
