# Generated by Django 5.0.2 on 2024-05-29 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0023_alter_emp_leave_balance_master_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_config_details',
            name='IsAutoCredit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 902938)),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 902938)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 902938)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 902938)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 904969)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 904969)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 904969)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='End_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 904969)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 904969)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='Start_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 904969)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 892880)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 892880)),
        ),
        migrations.AlterField(
            model_name='national_holidays',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 892880)),
        ),
        migrations.AlterField(
            model_name='national_holidays',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 892880)),
        ),
        migrations.AlterField(
            model_name='optional_holidays',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
        migrations.AlterField(
            model_name='optional_holidays',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 18, 38, 49, 894898)),
        ),
    ]
