# Generated by Django 5.0.2 on 2025-05-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0033_leave_application_actiondatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='emp_leave_balance_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='empmonthlevelcreditmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='empmonthleveldebitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 292275)),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 292275)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='leave_config_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='leave_process_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='leave_process_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 290273)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='leave_type_master',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='national_holidays',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='national_holidays',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='optional_holidays',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
        migrations.AlterField(
            model_name='optional_holidays',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 287754)),
        ),
    ]
