# Generated by Django 5.0.2 on 2025-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0038_alter_emp_leave_balance_master_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_config_details',
            name='MonthlyLeave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
