# Generated by Django 5.0.2 on 2026-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0039_leave_config_details_monthlyleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='optional_holidays',
            name='HotelID',
            field=models.BigIntegerField(default=0),
        ),
    ]
