# Generated by Django 5.0.2 on 2026-01-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0040_optional_holidays_hotelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='national_holidays',
            name='HotelID',
            field=models.BigIntegerField(default=0),
        ),
    ]
