# Generated by Django 5.0.2 on 2026-01-19 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0042_state_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Off_Assign_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(db_index=True, max_length=255)),
                ('EmployeeCode', models.CharField(db_index=True, max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('Is_Assigned', models.BooleanField(db_index=True, default=False)),
                ('Description', models.TextField()),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
