# Generated by Django 5.0.2 on 2026-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0043_comp_off_assign_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_off_assign_logs',
            name='Month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comp_off_assign_logs',
            name='Year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comp_off_assign_logs',
            name='EmpID',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comp_off_assign_logs',
            name='EmployeeCode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comp_off_assign_logs',
            name='Message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
