# Generated by Django 5.0.2 on 2026-01-20 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_Management_System', '0044_comp_off_assign_logs_month_comp_off_assign_logs_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp_off_assign_logs',
            name='Description',
        ),
        migrations.AddField(
            model_name='comp_off_assign_logs',
            name='Leave_Type_Master',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Leave_Management_System.leave_type_master'),
            preserve_default=False,
        ),
    ]
