# Generated by Django 4.1.7 on 2023-07-06 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSignageEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FixedSignageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FixedSignageEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('FixedSignageEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.fixedsignageentrymaster')),
                ('FixedSignageMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.fixedsignagemaster')),
            ],
        ),
    ]
