# Generated by Django 4.1.7 on 2023-07-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0002_indicativeproimpentrymaster_indicativeproimpmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicativeproimpentrymaster',
            name='TotalIndProjTimeFrame',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
