# Generated by Django 4.1.7 on 2023-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0003_indicativeproimpentrymaster_totalindprojtimeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicativeproimpentrymaster',
            name='Months',
            field=models.BigIntegerField(default=0, max_length=20),
        ),
    ]
