# Generated by Django 4.1.7 on 2023-07-07 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0004_indicativeproimpentrymaster_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnagListEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('Yes', models.BooleanField()),
                ('No', models.BooleanField()),
                ('Remarks', models.TextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SnagListMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SnagListEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('SnagListEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.snaglistentrymaster')),
                ('SnagListMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.snaglistmaster')),
            ],
        ),
    ]
