# Generated by Django 4.1.7 on 2023-07-08 05:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0005_snaglistentrymaster_snaglistmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaglistentrymaster',
            name='Area',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snaglistentrymaster',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
