# Generated by Django 4.1.7 on 2023-07-08 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0006_snaglistentrymaster_area_snaglistentrymaster_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaglistentrydetails',
            name='Remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='snaglistentrydetails',
            name='Yes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
