# Generated by Django 4.1.7 on 2023-07-08 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0007_snaglistentrydetails_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='Remarks',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
