# Generated by Django 4.1.7 on 2023-07-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0008_alter_snaglistentrydetails_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snaglistentrymaster',
            name='No',
        ),
        migrations.RemoveField(
            model_name='snaglistentrymaster',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='snaglistentrymaster',
            name='Yes',
        ),
    ]
