# Generated by Django 4.1.7 on 2023-07-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0009_remove_snaglistentrymaster_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snaglistentrymaster',
            name='EntryMonth',
        ),
        migrations.RemoveField(
            model_name='snaglistentrymaster',
            name='EntryYear',
        ),
    ]
