# Generated by Django 4.1.7 on 2023-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0010_remove_snaglistentrymaster_entrymonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaglistentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snaglistentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0),
        ),
    ]
