# Generated by Django 4.1.7 on 2023-07-10 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0012_projectimpprocessmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImpProcessEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=200)),
                ('StartDate', models.DateField(default=datetime.date.today)),
                ('ForecastCompletionDate', models.DateField(default=datetime.date.today)),
                ('Attention', models.CharField(max_length=200)),
                ('Issue', models.CharField(max_length=200)),
                ('By', models.CharField(max_length=200)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('ResponseTime', models.CharField(max_length=200)),
                ('CompletionBy', models.CharField(max_length=200)),
                ('Remarks', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
