# Generated by Django 4.1.7 on 2023-07-10 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0013_projectimpprocessentrymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimpprocessentrymaster',
            name='CompletionBy',
        ),
        migrations.RemoveField(
            model_name='projectimpprocessentrymaster',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='projectimpprocessentrymaster',
            name='ResponseTime',
        ),
        migrations.CreateModel(
            name='ProjectImpProcessEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResponseTime', models.CharField(max_length=200)),
                ('Remarks', models.CharField(max_length=200)),
                ('CompletionBy', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ProjectImpProcessEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.projectimpprocessentrymaster')),
                ('ProjectImpProcessMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.projectimpprocessmaster')),
            ],
        ),
    ]
