# Generated by Django 4.1.7 on 2023-07-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0014_remove_projectimpprocessentrymaster_completionby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimpprocessentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectimpprocessentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0),
        ),
    ]
