# Generated by Django 4.1.7 on 2023-07-10 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0015_projectimpprocessentrymaster_entrymonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimpprocessentrydetails',
            name='ActionBy',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
