# Generated by Django 4.1.7 on 2023-07-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0016_projectimpprocessentrydetails_actionby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimpprocessentrydetails',
            name='ActionBy',
        ),
        migrations.RemoveField(
            model_name='projectimpprocessentrymaster',
            name='TotalAmount',
        ),
    ]
