# Generated by Django 4.1.7 on 2023-07-11 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0018_hotelhandovermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelHandOverEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
