# Generated by Django 4.1.7 on 2023-07-11 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0019_hotelhandoverentrymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandOverEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeeksBefore', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100)),
                ('Remarks', models.TextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('HotelHandOverEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.hotelhandoverentrymaster')),
                ('HotelHandOverMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.hotelhandovermaster')),
            ],
        ),
    ]
