# Generated by Django 4.1.7 on 2023-07-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0020_handoverentrydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverentrydetails',
            name='WeeksBefore',
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='Months',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='TotalIndProjTimeFrame',
            field=models.IntegerField(default=0),
        ),
    ]
