# Generated by Django 4.1.7 on 2023-07-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0021_remove_handoverentrydetails_weeksbefore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snaglistentrymaster',
            name='TotalAmount',
        ),
    ]
