# Generated by Django 4.1.7 on 2023-07-13 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0023_divisionmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('DivisionMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.divisionmaster')),
            ],
        ),
    ]
