# Generated by Django 4.1.7 on 2023-07-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0025_snaglistmaster_sectionmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snaglistmaster',
            name='SectionMaster',
        ),
    ]
