# Generated by Django 4.1.7 on 2023-07-13 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0026_remove_snaglistmaster_sectionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaglistmaster',
            name='SectionMaster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.sectionmaster'),
            preserve_default=False,
        ),
    ]
