# Generated by Django 4.1.7 on 2023-07-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0027_snaglistmaster_sectionmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionmaster',
            name='category',
        ),
    ]
