# Generated by Django 4.1.7 on 2023-07-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0028_remove_divisionmaster_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmaster',
            name='category',
        ),
    ]
