# Generated by Django 4.1.8 on 2023-07-21 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0029_remove_sectionmaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionmaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrydetails',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrydetails',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrydetails',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrydetails',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrydetails',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignageentrymaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fixedsignagemaster',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='handoverentrydetails',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='handoverentrydetails',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='handoverentrydetails',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='handoverentrydetails',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='handoverentrydetails',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='handoverentrydetails',
            name='Remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandoverentrymaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandovermaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandovermaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandovermaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandovermaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hotelhandovermaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrydetails',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrydetails',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrydetails',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrydetails',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrydetails',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='Months',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpentrymaster',
            name='TotalIndProjTimeFrame',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='IsDelete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indicativeproimpmaster',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='CompletionBy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='Remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrydetails',
            name='ResponseTime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='Attention',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='By',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='Date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='ForecastCompletionDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='Issue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='Project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessentrymaster',
            name='StartDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='ActionBy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimpprocessmaster',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sectionmaster',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrydetails',
            name='Remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='Area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='Date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='EntryMonth',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='EntryYear',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistentrymaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='OrganizationID',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snaglistmaster',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
