# Generated by Django 4.1.8 on 2023-07-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0030_alter_divisionmaster_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaglistentrymaster',
            name='SectionMaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PreOpeningDoc.sectionmaster'),
            preserve_default=False,
        ),
    ]
