# Generated by Django 4.1.8 on 2023-07-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0031_snaglistentrymaster_sectionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaglistmaster',
            name='worktype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
