# Generated by Django 4.1.8 on 2023-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreOpeningDoc', '0032_snaglistmaster_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaglistmaster',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
