# Generated by Django 4.1.8 on 2023-06-22 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAbscondingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Emp_Code', models.CharField(max_length=100)),
                ('DOJ', models.DateField(default=datetime.date.today)),
                ('Date_Of_Absconding', models.DateField(default=datetime.date.today)),
                ('Dept', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=500)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
