# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAbsconding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empshowcausenotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Emp_Code', models.CharField(max_length=100)),
                ('DOJ', models.DateField(default=datetime.date.today)),
                ('Date_Of_absence', models.DateField(default=datetime.date.today)),
                ('Dept', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=500)),
                ('Issuing_manager_name', models.CharField(default='', max_length=255)),
                ('Issuing_designation', models.CharField(default='', max_length=255)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='empabscondingmodel',
            name='Issuing_designation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empabscondingmodel',
            name='Issuing_manager_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empabscondingmodel',
            name='showcause',
            field=models.BooleanField(default=False),
        ),
    ]
