# Generated by Django 5.0.2 on 2025-01-14 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAbsconding', '0002_empshowcausenotice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empshowcausenotice',
            name='NoticeCreateddate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='empshowcausenotice',
            name='NoticeIssuingdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='Issuing_designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='Issuing_manager_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='Issuing_designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='Issuing_manager_name',
            field=models.CharField(max_length=255),
        ),
    ]
