# Generated by Django 5.0.2 on 2025-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAbsconding', '0003_empshowcausenotice_noticecreateddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empabscondingmodel',
            name='LastEmpStatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
