# Generated by Django 5.0.2 on 2025-06-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAbsconding', '0004_empabscondingmodel_lastempstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='empabscondingmodel',
            name='AbscondingRevoke',
            field=models.BooleanField(default=False),
        ),
    ]
