# Generated by Django 5.0.2 on 2025-11-05 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAbsconding', '0005_empabscondingmodel_abscondingrevoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='DOJ',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='Date_Of_Absconding',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empabscondingmodel',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='DOJ',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='Date_Of_absence',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='NoticeCreateddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='NoticeIssuingdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empshowcausenotice',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
