from datetime import date
from django.db import models

class Outlet(models.Model):
    title = models.CharField(max_length = 200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
class Expenses(models.Model):
    title = models.CharField(max_length = 200)
    

class PayrollExpenses(models.Model):
    title = models.CharField(max_length = 200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    

    
class PayrollExpensesEntry(models.Model):
    ExpenseID =models.ForeignKey(PayrollExpenses, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
class  PLUtilitiesMaster(models.Model):
    title = models.CharField(max_length = 200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
class PLUtilitiesEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    TotalAmount  = models.DecimalField(decimal_places=2,max_digits=12 )
    IsDelete = models.BooleanField(default=False)
    
  
class PLUtilitiesEntryDetails(models.Model):
    PLUtilitiesMaster =models.ForeignKey(PLUtilitiesMaster, on_delete=models.CASCADE)
    PLUtilitiesEntryMaster =models.ForeignKey(PLUtilitiesEntryMaster, on_delete=models.CASCADE)
    PLUtilities_Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
class PL_Engineering_Master(models.Model):
    title = models.CharField(max_length =  200 , blank=True)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class PL_Engineering_Entry_Master(models.Model):
    EntryMonth =models.BigIntegerField(default=0, blank=True )
    EntryYear =models.BigIntegerField(default=0, blank=True)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    TraineeStaff = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    PayrollAndRelatedExpenses = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    PL_Engineering_Related_Expenses = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Total_Other_Expenses = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    TotalExpenses = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)  
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
class PL_Engineering_EntryDetails(models.Model):
    PL_Engineering_Master =models.ForeignKey(PL_Engineering_Master, on_delete=models.CASCADE,blank=True)
    PL_Engineering_Entry_Master =models.ForeignKey(PL_Engineering_Entry_Master, on_delete=models.CASCADE,blank=True)
    PL_Engineering_Amount = models.DecimalField(decimal_places=2,max_digits=12,default=0,null=True,blank=True)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
    
class AG_SecurityMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)   
    
class AG_SecurityEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0 ,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places = 2 , max_digits = 12)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places = 2 , max_digits = 12)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places = 2, max_digits = 12)
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places = 2, max_digits = 12)
    TotalExpenses = models.DecimalField(default = 0 ,  decimal_places = 2, max_digits = 12)   
    OrganizationID = models.BigIntegerField(default=0 )
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class AG_SecurityEntryDetails(models.Model):
    AG_SecurityMaster =models.ForeignKey(AG_SecurityMaster, on_delete=models.CASCADE)
    AG_SecurityEntryMaster =models.ForeignKey(AG_SecurityEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
class AG_HRMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)  
    
    
class AG_HREntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
  
class AG_HREntryDetails(models.Model):
    AG_HRMaster =models.ForeignKey(AG_HRMaster, on_delete=models.CASCADE)
    AG_HREntryMaster =models.ForeignKey(AG_HREntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    
    
class Total_AG_Master(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)  


class Total_AGEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)

class Total_AGEntryDetails(models.Model):
    Total_AG_Master =models.ForeignKey(Total_AG_Master, on_delete=models.CASCADE)
    Total_AGEntryMaster =models.ForeignKey(Total_AGEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
 
    
    
class SM_SalesExpenseMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class SM_MarketingExpenseMaster(models.Model):
    Mtitle = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)   
  
class SM_SaleMarketingEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Sales_Expenses =  models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Marketing_Expenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False) 
     
class SM_SalesEntryDetails(models.Model):
    SM_SalesExpenseMaster =models.ForeignKey(SM_SalesExpenseMaster, on_delete=models.CASCADE)
    SM_SaleMarketingEntryMaster =models.ForeignKey(SM_SaleMarketingEntryMaster, on_delete=models.CASCADE)
    AmountSales = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
        
class SM_MarketingEntryDetails(models.Model):
    SM_MarketingExpenseMaster =models.ForeignKey(SM_MarketingExpenseMaster, on_delete=models.CASCADE)
    SM_SaleMarketingEntryMaster =models.ForeignKey(SM_SaleMarketingEntryMaster, on_delete=models.CASCADE)
    AmountMarketing = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    



 
    
class ItServiceMaster(models.Model):
    title_1 = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class ItSystemExpenseMaster(models.Model):
    title_2 = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
 
class IT_EntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    Total_Cost_Of_Services =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False) 
    
    
class It_ServiceEntryDetails(models.Model):
    ItServiceMaster =models.ForeignKey(ItServiceMaster, on_delete=models.CASCADE)
    IT_EntryMaster =models.ForeignKey( IT_EntryMaster, on_delete=models.CASCADE)
    AmountServices = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
        
class It_SystemExpenseEntryDetails(models.Model):
    ItSystemExpenseMaster =models.ForeignKey(ItSystemExpenseMaster, on_delete=models.CASCADE)
    IT_EntryMaster =models.ForeignKey( IT_EntryMaster, on_delete=models.CASCADE)
    AmountSystemExpense = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
   
   
    
    
class AG_Analysis_Master(models.Model):
    title_1 = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
       
class AG_RatioAnalysis_Master(models.Model):
    title_2 = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class AG_AnalysisEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SalaryAndWages = models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives = models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True)
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False) 
       
class AG_AnalysisEntryDetail(models.Model):
    AG_Analysis_Master =models.ForeignKey(AG_Analysis_Master, on_delete=models.CASCADE)
    AG_AnalysisEntryMaster =models.ForeignKey( AG_AnalysisEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
   


 
class Rental_Other_IncomeMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
          
class Rental_Other_IncomeEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    Rental_And_OtherIncome = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
  
class Rental_Other_IncomeEntryDetail(models.Model):
    Rental_Other_IncomeMaster =models.ForeignKey(Rental_Other_IncomeMaster, on_delete=models.CASCADE)
    Rental_Other_IncomeEntryMaster =models.ForeignKey(Rental_Other_IncomeEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    

 
class OOD_LaundryMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
           
class OOD_LaundryEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    Dry_CleaningServices = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    LaundryServices =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    GuestLaundryRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Cost_OfLaundryServices =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Total_CostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Gross_Profit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
 
class OOD_LaundryEntryDetail(models.Model):
    OOD_LaundryMaster =models.ForeignKey(OOD_LaundryMaster, on_delete=models.CASCADE)
    OOD_LaundryEntryMaster =models.ForeignKey(OOD_LaundryEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
           
           

 
class OOD_TransportMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
       
class OOD_TransportEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    ExternalGuestTransportation =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    GuestTransportRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Cost_OfGuestTransportation =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Total_CostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Gross_Profit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
 
class OOD_TransportEntryDetail(models.Model):
    OOD_TransportMaster =models.ForeignKey(OOD_TransportMaster, on_delete=models.CASCADE)
    OOD_TransportEntryMaster =models.ForeignKey(OOD_TransportEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
                   

class OOD_HealthMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  
class OOD_HealthEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SpaTreatmentRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    HealthClubAndSpaRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Cost_OfMerchandise =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Total_CostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Gross_Profit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses = models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class OOD_HealthEntryDetail(models.Model):
    OOD_HealthMaster =models.ForeignKey(OOD_HealthMaster, on_delete=models.CASCADE)
    OOD_HealthEntryMaster =models.ForeignKey(OOD_HealthEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    

class FB_BanquetMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class FB_BanquetEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    HallRental =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_RevenueMisc =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
  
class FB_BanquetEntryDetail(models.Model):
    FB_BanquetMaster =models.ForeignKey(FB_BanquetMaster, on_delete=models.CASCADE)
    FB_BanquetEntryMaster =models.ForeignKey(FB_BanquetEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    



class FB_IRDMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class FB_IRDEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    RoomHireRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    AudioVisualRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    ServiceChargeRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    FB_Revenue_Others =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class FB_IRDEntryDetail(models.Model):
    FB_IRDMaster =models.ForeignKey(FB_IRDMaster, on_delete=models.CASCADE)
    FB_IRDEntryMaster =models.ForeignKey(FB_IRDEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    



class Outlet_1Master(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
     
class Outlet_1EntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    MealPlan =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    AudioVisualRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    FB_Revenue_Others =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class Outlet_1EntryDetail(models.Model):
    Outlet_1Master =models.ForeignKey(Outlet_1Master, on_delete=models.CASCADE)
    Outlet_1EntryMaster =models.ForeignKey(Outlet_1EntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
    


class Outlet_2Master(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
     
class Outlet_2EntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    RoomHireRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    AudioVisualRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    ServiceChargeRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    FB_Revenue_Others =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class Outlet_2EntryDetail(models.Model):
    Outlet_2Master =models.ForeignKey(Outlet_2Master, on_delete=models.CASCADE)
    Outlet_2EntryMaster =models.ForeignKey(Outlet_2EntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  
  
  

  


class Outlet_3Master(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
     
class Outlet_3EntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    RoomHireRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    AudioVisualRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    ServiceChargeRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    FB_Revenue_Others =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class Outlet_3EntryDetail(models.Model):
    Outlet_3Master =models.ForeignKey(Outlet_3Master, on_delete=models.CASCADE)
    Outlet_3EntryMaster =models.ForeignKey(Outlet_3EntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  
  
  
  
  


class Outlet_4Master(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
     
class Outlet_4EntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    RoomHireRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    AudioVisualRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    ServiceChargeRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    FB_Revenue_Others =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class Outlet_4EntryDetail(models.Model):
    Outlet_4Master =models.ForeignKey(Outlet_4Master, on_delete=models.CASCADE)
    Outlet_4EntryMaster =models.ForeignKey(Outlet_4EntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  

  
  
class Outlet_5Master(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
     
class Outlet_5EntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBEVERAGEREVENUE =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    RoomHireRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    AudioVisualRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    ServiceChargeRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    FB_Revenue_Others =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    FB_Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    BeverageCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalCostOfFBSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSale =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FB_OtherCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOf_OtherRev =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)
    TotalCostOfSales =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GrossProfit =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True) 
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class Outlet_5EntryDetail(models.Model):
    Outlet_5Master =models.ForeignKey(Outlet_5Master, on_delete=models.CASCADE)
    Outlet_5EntryMaster =models.ForeignKey(Outlet_5EntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  


 
class PL_RoomsMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)

class PL_RoomsEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    TransientRoomRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TransientRoomRevenueSez =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    ClubMisc_O =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    RoomRevenueExtraBedCharge =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    TotalRoomRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses =  models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class PL_RoomsEntryDetail(models.Model):
    PL_RoomsMaster =models.ForeignKey(PL_RoomsMaster, on_delete=models.CASCADE)
    PL_RoomsEntryMaster =models.ForeignKey(PL_RoomsEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  


class Total_OODMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
    
class Total_OODEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    SpaTreatmentRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Mod_ExtGuestTransportation =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    GuestLaundryRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    Revenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    Cost_OfMerchandise =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    Cost_OfGuestTransportation =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Cost_OfLaundryServices =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Total_CostOfSales =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    GrossProfit =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    SalaryAndWages = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    TotalExpenses =  models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    DepartmentIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
     
class Total_OODEntryDetail(models.Model):
    Total_OODMaster =models.ForeignKey(Total_OODMaster, on_delete=models.CASCADE)
    Total_OODEntryMaster =models.ForeignKey(Total_OODEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  
  
   

class PL_SummaryMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)  
    
class PL_SummaryEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    RoomsRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    FoodAndBeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    OtherOperatedDepartmentRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    RentalsAndOtherIncome =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    RoomExpenses =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    FoodAndBeverageExpenses =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    OtherOperatedDepartmentExpenses =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Total_DepartmentalExpenses =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Total_DepartmentalIncome =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    AdministrationAndGeneral = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    InformationAndTelecommunicationsSystem= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    SalesAndMarketing = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    PropertyOperartionAndMaintenance = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    Utilities = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    TotalUndistributedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    GrossOperatingProfit = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    GOP =  models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)      
     
class PL_SummaryEntryDetail(models.Model):
    PL_SummaryMaster =models.ForeignKey(PL_SummaryMaster, on_delete=models.CASCADE)
    PL_SummaryEntryMaster =models.ForeignKey(PL_SummaryEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  
  
  

class Total_FBMaster(models.Model):
    title = models.CharField(max_length =  200)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False) 
     
class Total_FBEntryMaster(models.Model):
    EntryMonth =models.BigIntegerField(default=0)
    EntryYear =models.BigIntegerField(default=0)
    FoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalFoodRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True) 
    BeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    TotalBeverageRevenue =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)  
    AudioVisualEquipmentCostOfSales1 =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)   
    FB_OtherCostOfSales1 =  models.DecimalField(default = 0 ,decimal_places = 2, max_digits =12,blank=True)       
    HallRental =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    FB_Revenue_MISC =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    TotalOtherIncome =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    FB_Revenue =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    FoodCostOfSales = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    BeverageCostOfSales= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    TotalCostOfFBSales = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    AudioVisualEquipmentCostOfSales2 = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    FB_OtherCostOfSales2 = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    TotalCostOfOtherRev = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    TotalCostOfSales = models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    GrossProfit =  models.DecimalField(default = 0 , decimal_places= 2, max_digits =12 ,blank=True)
    SalaryAndWages =  models.DecimalField(default = 0, blank=True,decimal_places = 2 , max_digits = 12)
    Bonuses_and_Incentives= models.DecimalField(default = 0 ,decimal_places = 2 , max_digits = 12)
    Salary_Wages_and_Bonuses = models.DecimalField(default = 0,blank=True,decimal_places = 2, max_digits = 12)
    EmployeeBenefits = models.DecimalField(default = 0 , decimal_places=2, max_digits = 12, blank=True)
    PayrollRelatedExpenses = models.DecimalField(default=0 , decimal_places =2 , max_digits=12 ,blank=True)
    PayrollAndRelatedExpenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Total_Other_Expenses = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    DepartmentIncome = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    RoomsAvailable = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    RoomsOccupied = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    Occupany = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    NumberOfGuests = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    NoOfFoodCovers = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    NoOfBeverageCovers = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    AveFoodPerCoverage = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    AveBeveragePerCoverage = models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    AveFoodAndBeveragePerCoverage =models.DecimalField(default=0 , decimal_places =2, max_digits = 12,blank=True) 
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)     
    
class Total_FBEntryDetail(models.Model):
    Total_FBMaster =models.ForeignKey(Total_FBMaster, on_delete=models.CASCADE)
    Total_FBEntryMaster =models.ForeignKey(Total_FBEntryMaster, on_delete=models.CASCADE)
    Amount = models.DecimalField(decimal_places=2,max_digits=12)
    OrganizationID = models.BigIntegerField(default=0)
    CreatedBy = models.BigIntegerField(default=0)
    CreatedDateTime = models.DateField(default = date.today)
    ModifyBy = models.BigIntegerField(default=0)
    ModifyDateTime = models.DateField(default = date.today)
    IsDelete = models.BooleanField(default=False)
  
  