# Generated by Django 4.1.7 on 2023-04-25 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Full_and_Final_Settltment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Emp_Code', models.CharField(max_length=100)),
                ('DOJ', models.DateField(default=datetime.date.today)),
                ('Date_Of_Leaving', models.DateField(default=datetime.date.today)),
                ('Dept', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Absconding', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Notice_Days_Served', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Resignation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Deduction_from_salary_PL', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Confirmed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Current_Salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Terminated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Laid_Off', models.CharField(max_length=100)),
                ('LS_Period', models.DateField(default=datetime.date.today)),
                ('LS_Opening_Balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('LS_Leaved_Earned', models.CharField(max_length=100)),
                ('LS_Leaved_Availed', models.CharField(max_length=100)),
                ('LS_PL_Bal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PL_Total_PL', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PL_Basic_Salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PL_Rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PL_Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('NPP_Total_Notice_Pay_Days', models.CharField(max_length=100)),
                ('NPP_Gross', models.DecimalField(decimal_places=2, max_digits=6)),
                ('NPP_Rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('NPP_Net_Amount_Paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('GP_No_Of_Years', models.CharField(max_length=100)),
                ('GP_Last_Basics', models.DecimalField(decimal_places=2, max_digits=6)),
                ('GP_Graturity_Days', models.CharField(max_length=100)),
                ('GP_Graturity_Payments', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_Pending_Salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_PL', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_Gratuity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_Grand_Total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_Deductions', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_Uniform_Deductions', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FFPS_Payable_Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
