# Generated by Django 4.1.7 on 2023-04-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_and_final_settltment',
            name='LS_Period',
        ),
    ]
