# Generated by Django 4.1.7 on 2023-04-25 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0002_remove_full_and_final_settltment_ls_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='LS_Period',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
