# Generated by Django 4.1.8 on 2023-06-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0003_full_and_final_settltment_ls_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Current_Salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Deduction_from_salary_PL',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Deductions',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Grand_Total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Gratuity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_PL',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Payable_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Pending_Salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Uniform_Deductions',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='GP_Graturity_Payments',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='GP_Last_Basics',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_Opening_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_PL_Bal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Gross',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Net_Amount_Paid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Basic_Salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Total_PL',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
