# Generated by Django 4.1.8 on 2023-06-28 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0004_alter_full_and_final_settltment_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='DOJ',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
