# Generated by Django 4.1.8 on 2023-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0005_alter_full_and_final_settltment_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedBy',
            field=models.CharField(choices=[('Auditor', 'Auditor'), ('Finance', 'Finance')], default='Finance', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='FinalStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PaymentPaidAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PaymentPaidDate',
            field=models.DateField(blank=True,  null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PaymentRemarks',
            field=models.CharField(blank=True,null=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PaymentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50),
            preserve_default=False,
        ),
    ]
