# Generated by Django 4.1.8 on 2023-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0006_full_and_final_settltment_auditedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PaymentPaidDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
