# Generated by Django 4.1.8 on 2023-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0007_alter_full_and_final_settltment_paymentpaiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PaymentPaidDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
