# Generated by Django 4.1.8 on 2023-11-11 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0009_alter_full_and_final_settltment_paymentremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='FinalStatusUpdateDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
