# Generated by Django 4.1.8 on 2023-11-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0010_full_and_final_settltment_finalstatusupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PaymentPaidAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PaymentPaidDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
