# Generated by Django 5.0.2 on 2025-01-14 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0011_alter_full_and_final_settltment_paymentpaidamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Absconding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='AuditedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Confirmed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='CreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='CreatedDateTime',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Current_Salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Deduction_from_salary_PL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Dept',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Designation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Emp_Code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Grand_Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Gratuity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_PL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Payable_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Pending_Salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FFPS_Uniform_Deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FinalStatus',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FinalStatusUpdateDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='GP_Graturity_Days',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='GP_Graturity_Payments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='GP_Last_Basics',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='GP_No_Of_Years',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_Leaved_Availed',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_Leaved_Earned',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_Opening_Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_PL_Bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_Period',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Laid_Off',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='ModifyBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='ModifyDateTime',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Net_Amount_Paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='NPP_Total_Notice_Pay_Days',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Notice_Days_Served',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='OrganizationID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Basic_Salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PL_Total_PL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PaymentRemarks',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='PaymentStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Resignation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Terminated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
