# Generated by Django 5.0.2 on 2025-06-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0012_alter_full_and_final_settltment_absconding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Accounts_Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Advance_Salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Advance_Salary_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Branch_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Deduction_from_salary_PL_Boolean',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Final_PL_Payment_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Graturity_Payments_Earning_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='IFSCCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='LTARATE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='LTA_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='LTA_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Leave_PL_From_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Leave_PL_To_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Notice_Period_Deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Notice_Period_Deductions_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='OtherDeductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Other_Deductions_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Other_Earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Other_Earnings_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PRORATABASISPAYMENT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Pending_Salary_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Remaining_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='TOTALDAYSWORKED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='TOTALMONTHSWORKED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_Advance_Paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_Advance_Taken',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_Deductions_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_Earning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_Earning_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_Notice_Days_Served',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Uniform_Deductions_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
