# Generated by Django 5.0.2 on 2025-06-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0013_full_and_final_settltment_accounts_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='full_and_final_settltment',
            old_name='LTARATE',
            new_name='LTA_Rate',
        ),
        migrations.RenameField(
            model_name='full_and_final_settltment',
            old_name='PRORATABASISPAYMENT',
            new_name='Pro_Rata_Basis_Payment',
        ),
        migrations.RenameField(
            model_name='full_and_final_settltment',
            old_name='TOTALDAYSWORKED',
            new_name='Total_Days_Worked',
        ),
        migrations.RenameField(
            model_name='full_and_final_settltment',
            old_name='TOTALMONTHSWORKED',
            new_name='Total_Months_Worked',
        ),
    ]
