# Generated by Django 5.0.2 on 2025-06-10 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0014_rename_ltarate_full_and_final_settltment_lta_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedByFinance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedByFinance_Date_Time',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedByGM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedByGM_Date_Time',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedByHR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedByHR_Date_Time',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PaymentStatus_Date_Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
