# Generated by Django 5.0.2 on 2025-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0015_full_and_final_settltment_auditedbyfinance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedBy_Auditor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='AuditedBy_Auditor_Date_Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
