# Generated by Django 5.0.2 on 2025-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0016_full_and_final_settltment_auditedby_auditor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Employee_PF_Amount_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PT_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='PT_Amount_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
