# Generated by Django 5.0.2 on 2025-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0017_full_and_final_settltment_employee_pf_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Total_PL_Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
