# Generated by Django 5.0.2 on 2025-11-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0018_full_and_final_settltment_total_pl_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='EmpStatus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='Emp_Resignation_Date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
