# Generated by Django 5.0.2 on 2025-11-09 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0019_full_and_final_settltment_empstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='AuditedByFinance_Date_Time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='AuditedByGM_Date_Time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='AuditedByHR_Date_Time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='CreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='DOJ',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='Date_Of_Leaving',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='FinalStatusUpdateDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='LS_Period',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='full_and_final_settltment',
            name='ModifyDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
