# Generated by Django 5.0.2 on 2025-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullandFinalSettlement', '0020_alter_full_and_final_settltment_auditedbyfinance_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='full_and_final_settltment',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
