# Generated by Django 4.1.7 on 2023-07-03 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseReport', '0004_it_entrymaster_itservicemaster_itsystemexpensemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AG_SecurityEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('Bonuses_and_Incentives', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('EmployeeBenefits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('PayrollRelatedExpenses', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('PayrollAndRelatedExpenses', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Total_Other_Expenses', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('TotalExpenses', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AG_SecurityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AG_SecurityEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('AG_SecurityEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseReport.ag_securityentrymaster')),
                ('AG_SecurityMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseReport.ag_securitymaster')),
            ],
        ),
    ]
