# Generated by Django 4.1.7 on 2023-07-04 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseReport', '0013_fb_banquetentrymaster_fb_banquetmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet_1EntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('FoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('MealPlan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalFoodRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalBEVERAGEREVENUE', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue_Others', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalOtherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_Revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FoodCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('BeverageCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfFBSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AudioVisualEquipmentCostOfSale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FB_OtherCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOf_OtherRev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalCostOfSales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GrossProfit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('SalaryAndWages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Bonuses_and_Incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Salary_Wages_and_Bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('EmployeeBenefits', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PayrollAndRelatedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_Other_Expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('DepartmentIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet_1Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet_1EntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Outlet_1EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseReport.outlet_1entrymaster')),
                ('Outlet_1Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseReport.outlet_1master')),
            ],
        ),
    ]
