# Generated by Django 4.1.7 on 2023-07-04 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseReport', '0020_pl_roomsentrymaster_pl_roomsmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PL_SummaryEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryMonth', models.BigIntegerField(default=0)),
                ('EntryYear', models.BigIntegerField(default=0)),
                ('RoomsRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FoodAndBeverageRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OtherOperatedDepartmentRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('RentalsAndOtherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalRevenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('RoomExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('FoodAndBeverageExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OtherOperatedDepartmentExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_DepartmentalExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Total_DepartmentalIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('AdministrationAndGeneral', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('InformationAndTelecommunicationsSystem', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('SalesAndMarketing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('PropertyOperartionAndMaintenance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('Utilities', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('TotalUndistributedExpenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GrossOperatingProfit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('GOP', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PL_SummaryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PL_SummaryEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('PL_SummaryEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseReport.pl_summaryentrymaster')),
                ('PL_SummaryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseReport.pl_summarymaster')),
            ],
        ),
    ]
