# Generated by Django 5.0.2 on 2024-09-17 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('averages', models.JSONField()),
                ('source_counts', models.JSONField()),
                ('classification_counts', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField()),
                ('makemytrip_url', models.URLField(blank=True, max_length=2000)),
                ('tripadvisor_url', models.URLField(blank=True, max_length=2000)),
                ('booking_url', models.URLField(blank=True, max_length=2000)),
                ('agoda_url', models.URLField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField()),
                ('partner_type', models.CharField(blank=True, max_length=200)),
                ('overall_rating', models.FloatField(blank=True, null=True)),
                ('service', models.FloatField(blank=True, null=True)),
                ('room', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('cleanliness', models.FloatField(blank=True, null=True)),
                ('location', models.FloatField(blank=True, null=True)),
                ('facilities', models.FloatField(blank=True, null=True)),
                ('food', models.FloatField(blank=True, null=True)),
                ('wifi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='upload_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.FloatField(blank=True, null=True)),
                ('service', models.FloatField(blank=True, null=True)),
                ('room', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('cleanliness', models.FloatField(blank=True, null=True)),
                ('location', models.FloatField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('management_response', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('reply_date', models.DateField(blank=True, null=True)),
                ('reviwer', models.CharField(blank=True, max_length=255)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
