# Generated by Django 5.0.9 on 2024-09-17 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
       
      
    ]
