# Generated by Django 5.0.9 on 2024-09-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_partnerrating_cleanliness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrating',
            name='Activation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partnerrating',
            name='IsNileHotel',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload_data',
            name='Activation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload_data',
            name='IsNileHotel',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
