# Generated by Django 5.0.9 on 2024-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_partnerrating_activation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='reply_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
