# Generated by Django 5.0.9 on 2024-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_upload_data_cleanliness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='reviewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
