# Generated by Django 5.0.9 on 2024-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_upload_data_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerrating',
            name='Activation_status',
        ),
        migrations.RemoveField(
            model_name='partnerrating',
            name='IsNileHotel',
        ),
        migrations.RemoveField(
            model_name='upload_data',
            name='Activation_status',
        ),
        migrations.RemoveField(
            model_name='upload_data',
            name='IsNileHotel',
        ),
    ]
