# Generated by Django 5.0.2 on 2025-05-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_upload_data_reviewer'),
        ('review', '0009_remove_partnerrating_activation_status_and_more'),
    ]

    operations = [
    ]
