# Generated by Django 5.0.2 on 2025-05-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_merge_20250515_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='organizationurls',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationurls',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='organizationurls',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationurls',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationurls',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='partnerrating',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerrating',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='partnerrating',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerrating',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerrating',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='upload_data',
            name='reply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
