# Generated by Django 5.0.2 on 2025-05-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_fileupload_createdby_fileupload_createddatetime_and_more'),
        ('review', '0011_fileupload_createdby_fileupload_createddatetime_and_more'),
    ]

    operations = [
    ]
