# Generated by Django 5.0.2 on 2025-07-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_merge_20250517_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_data',
            name='reviwer',
        ),
    ]
