# Generated by Django 4.1.8 on 2023-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetteofPromotion', '0002_promotionletteremployeedetail_promotiondesignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionletteremployeedetail',
            name='emp_code',
            field=models.CharField(max_length=200),
        ),
    ]
