# Generated by Django 4.1.8 on 2023-12-30 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailReader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageID', models.CharField(max_length=1000)),
                ('To', models.CharField(max_length=1000)),
                ('Subject', models.CharField(max_length=1000)),
                ('Sender', models.CharField(max_length=1000)),
                ('ReceivedTime', models.CharField(max_length=1000)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
