# Generated by Django 4.1.8 on 2023-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailReader', '0002_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='MessageID',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='ReceivedTime',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='Sender',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='Subject',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='To',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
