# Generated by Django 4.1.8 on 2023-12-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailReader', '0004_alter_emailmessage_messageid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='MessageID',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
