# Generated by Django 5.0.2 on 2025-05-21 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('organization_id', models.BigIntegerField(default=0)),
                ('created_by', models.BigIntegerField(default=0)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_by', models.BigIntegerField(default=0)),
                ('modify_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TravelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_Date_from', models.DateField(blank=True, null=True)),
                ('travel_Date_to', models.DateField(blank=True, null=True)),
                ('travel_route_from', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_route_to', models.CharField(blank=True, max_length=255, null=True)),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('travel_mode', models.CharField(blank=True, choices=[('Train', 'Train'), ('Bus', 'Bus'), ('Flight', 'Flight')], max_length=10, null=True)),
                ('pnr', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('billing', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_id', models.BigIntegerField(default=0)),
                ('created_by', models.BigIntegerField(default=0)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_by', models.BigIntegerField(default=0)),
                ('modify_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Travel_Details.travelrequest')),
            ],
        ),
    ]
