# Generated by Django 5.0.2 on 2025-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelentry',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
