# Generated by Django 5.0.2 on 2025-05-26 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Details', '0002_alter_travelentry_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelentry',
            name='deleted_by',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelentry',
            name='deleted_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='deleted_by',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='deleted_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
