# Generated by Django 5.0.2 on 2025-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Details', '0004_alter_travelentry_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='deleted_by',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
