# Generated by Django 5.0.2 on 2025-07-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Details', '0005_alter_travelrequest_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelentry',
            name='travel_mode',
            field=models.CharField(blank=True, choices=[('Train', 'Train'), ('Bus', 'Bus'), ('Flight', 'Flight'), ('By Road', 'By Road')], max_length=10, null=True),
        ),
    ]
