# Generated by Django 4.1.7 on 2023-03-25 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='waterconsumptionreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnteryDate', models.DateField(default=datetime.date.today)),
                ('RawWaterPPM', models.CharField(max_length=100)),
                ('RawWaterpH', models.CharField(max_length=100)),
                ('RawWaterTDS', models.CharField(max_length=100)),
                ('SoftWaterPPM', models.CharField(max_length=100)),
                ('SoftWaterpH', models.CharField(max_length=100)),
                ('SoftWaterTDS', models.CharField(max_length=100)),
                ('ROWaterPPM', models.CharField(max_length=100)),
                ('ROWaterpH', models.CharField(max_length=100)),
                ('ROWaterTDS', models.CharField(max_length=100)),
                ('LaundryWaterPPM', models.CharField(max_length=100)),
                ('LaundryWaterpH', models.CharField(max_length=100)),
                ('LaundryWaterTDS', models.TextField(max_length=100)),
            ],
        ),
    ]
