# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manning_Guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 43, 10001)),
        ),
    ]
