# Generated by Django 5.0.2 on 2025-04-02 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manning_Guide', '0003_alter_contractdivisionmaster_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetinsurancecost',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='budgetinsurancecost',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='budgetmealcost',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='budgetmealcost',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contractdepartmentmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contractdepartmentmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='contractdepartmentmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contractdesignationmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contractdesignationmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='contractdesignationmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='corporatedepartmentmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='corporatedepartmentmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='corporatedepartmentmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='corporatedesignationmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='corporatedesignationmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='corporatedesignationmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entryactualcontract',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='entryactualcontract',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entryactualinsurancecost',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='entryactualinsurancecost',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entryactualmealcost',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='entryactualmealcost',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entryactualsharedservices',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='entryactualsharedservices',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='managebudgetcontract',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='managebudgetcontract',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='managebudgetonroll',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='managebudgetsharedservices',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='managebudgetsharedservices',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='modulemapping',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='modulemapping',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='onrolldepartmentmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='onrolldepartmentmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='onrolldepartmentmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='onrolldesignationmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='onrolldesignationmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='onrolldesignationmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='DivisionName',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicesdepartmentmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='servicesdepartmentmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='servicesdepartmentmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicesdesignationmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='servicesdesignationmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='servicesdesignationmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 16, 45, 43, 96962)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='Order',
            field=models.IntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
