# Generated by Django 5.0.2 on 2025-05-17 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manning_Guide', '0005_alter_budgetinsurancecost_isdelete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 942944)),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 942944)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 944948)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 944948)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 926828)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 926828)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 926828)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 926828)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 942944)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 4, 56, 942944)),
        ),
    ]
