# Generated by Django 5.0.2 on 2025-07-05 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manning_Guide', '0006_alter_contractdivisionmaster_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 7, 55, 769165)),
        ),
    ]
