# Generated by Django 5.0.2 on 2025-08-13 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manning_Guide', '0008_alter_contractdivisionmaster_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managebudgetonroll',
            name='Budget_Year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='contractdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='corporatedivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='laveladd',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='onrolldivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
        migrations.AlterField(
            model_name='servicesdivisionmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 55, 2, 878712)),
        ),
    ]
