# Generated by Django 5.0.2 on 2026-01-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manning_Guide', '0010_alter_contractdivisionmaster_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onrolldesignationmaster',
            name='Direct_Reporting_Designations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onrolldesignationmaster',
            name='Dotted_Line_Reporting_Designations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onrolldesignationmaster',
            name='Report_Designations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
