# Generated by Django 4.1.7 on 2023-04-24 03:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office_Snag_Registration_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Snag_Category_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Category_Title_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Snag_Category_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Yes', 'Yes'), ('NA', 'NA')], max_length=50)),
                ('Remarks', models.TextField()),
                ('Office_Snag_Registration_Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfficeSnaglist.office_snag_registration_form')),
                ('Snag_Category_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfficeSnaglist.snag_category_master')),
            ],
        ),
    ]
