# Generated by Django 4.1.7 on 2023-04-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRDcleranceform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ird_clerance',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
