# Generated by Django 5.0.2 on 2024-03-01 06:17

import Agreement.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Director_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Near_Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Name_of_Hotel', models.CharField(blank=True, max_length=255, null=True)),
                ('Number_of_Room', models.CharField(blank=True, max_length=255, null=True)),
                ('Years', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('sum_of_inr', models.CharField(blank=True, max_length=255, null=True)),
                ('license_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('Management_Services_N_N', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('end_date', models.DateField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('status', models.IntegerField(default=0)),
                ('Owner_Attention', models.CharField(blank=True, max_length=255, null=True)),
                ('Owner_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Owner_Tel_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Owner_Fax_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Owner_Email_Id', models.CharField(blank=True, max_length=255, null=True)),
                ('Operator_Attention', models.CharField(blank=True, max_length=255, null=True)),
                ('Operator_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Operator_Tel_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Operator_Fax_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Operator_Email_Id', models.CharField(blank=True, max_length=255, null=True)),
                ('Authorized_Director', models.CharField(blank=True, max_length=255, null=True)),
                ('Name_Witness1', models.CharField(blank=True, max_length=255, null=True)),
                ('Name_Witness2', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 728680))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 728680))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master_subartical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subartical_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_artical', models.CharField(blank=True, max_length=100, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artical_number', models.CharField(blank=True, max_length=20, null=True)),
                ('name_artical', models.CharField(blank=True, max_length=100, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 726681))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 726681))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master_childartical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childartical_number', models.CharField(blank=True, max_length=20, null=True)),
                ('child_artical', models.CharField(blank=True, max_length=100, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Master_subartical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agreement.master_subartical')),
            ],
        ),
        migrations.CreateModel(
            name='Master_subchildartical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childsubartical_number', models.CharField(blank=True, max_length=20, null=True)),
                ('childsub_artical', models.CharField(blank=True, max_length=100, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 727680))),
                ('IsDelete', models.BooleanField(default=False)),
                ('Master_childartical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agreement.master_childartical')),
            ],
        ),
        migrations.AddField(
            model_name='master_subartical',
            name='Master_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agreement.master_title'),
        ),
        migrations.CreateModel(
            name='uplodede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_filenn', models.FileField(blank=True, null=True, upload_to=Agreement.models.uplodede.unique_file_path)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 728680))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 11, 46, 57, 728680))),
                ('IsDelete', models.BooleanField(default=False)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agreement.agreement')),
            ],
        ),
    ]
