# Generated by Django 5.0.2 on 2024-03-01 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 750468)),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 750468)),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 750468)),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 750468)),
        ),
        migrations.AlterField(
            model_name='master_childartical',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 749461)),
        ),
        migrations.AlterField(
            model_name='master_childartical',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 749461)),
        ),
        migrations.AlterField(
            model_name='master_childartical',
            name='child_artical',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='master_subartical',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 748937)),
        ),
        migrations.AlterField(
            model_name='master_subartical',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 748937)),
        ),
        migrations.AlterField(
            model_name='master_subartical',
            name='sub_artical',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='master_subartical',
            name='subartical_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='master_subchildartical',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 749461)),
        ),
        migrations.AlterField(
            model_name='master_subchildartical',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 749461)),
        ),
        migrations.AlterField(
            model_name='master_subchildartical',
            name='childsub_artical',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='master_title',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 747209)),
        ),
        migrations.AlterField(
            model_name='master_title',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 747209)),
        ),
        migrations.AlterField(
            model_name='master_title',
            name='name_artical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uplodede',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 751469)),
        ),
        migrations.AlterField(
            model_name='uplodede',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 17, 16, 27, 751469)),
        ),
    ]
