# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0004_alter_agreement_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_childartical',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_childartical',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_subartical',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_subartical',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_subchildartical',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_subchildartical',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_title',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='master_title',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='uplodede',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
        migrations.AlterField(
            model_name='uplodede',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 879635)),
        ),
    ]
