# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationNameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationNameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotal_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_department', models.CharField(max_length=100)),
                ('Inteview_AssementID', models.IntegerField(blank=True)),
                ('Ref1_name', models.CharField(max_length=100)),
                ('Ref1_email', models.EmailField(max_length=254)),
                ('Ref1_mobile_number', models.CharField(max_length=15)),
                ('Ref1_Organization', models.CharField(max_length=255)),
                ('Ref1_Designation', models.CharField(max_length=255)),
                ('ref1_unique_id', models.CharField(max_length=20)),
                ('ref1_status', models.IntegerField(default=0)),
                ('Ref2_name', models.CharField(max_length=100)),
                ('Ref2_email', models.EmailField(max_length=254)),
                ('Ref2_mobile_number', models.CharField(max_length=15)),
                ('Ref2_Organization', models.CharField(max_length=255)),
                ('Ref2_Designation', models.CharField(max_length=255)),
                ('ref2_unique_id', models.CharField(max_length=20)),
                ('ref2_status', models.IntegerField(default=0)),
                ('Ref3_name', models.CharField(max_length=100)),
                ('Ref3_email', models.EmailField(max_length=254)),
                ('Ref3_mobile_number', models.CharField(max_length=15)),
                ('Ref3_Organization', models.CharField(max_length=255)),
                ('Ref3_Designation', models.CharField(max_length=255)),
                ('ref3_unique_id', models.CharField(max_length=20)),
                ('ref3_status', models.IntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 264904))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 264904))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reference_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_unique_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('relationship', models.TextField()),
                ('contact_informations', models.TextField()),
                ('this_company', models.BooleanField(default=False)),
                ('employment_from_date', models.DateField(blank=True, null=True)),
                ('employment_to_date', models.DateField(blank=True, null=True)),
                ('job_performance', models.CharField(max_length=250)),
                ('interpersonal_skills', models.CharField(max_length=250)),
                ('attendance_work', models.CharField(max_length=250)),
                ('leave_company', models.CharField(max_length=250)),
                ('rehire', models.BooleanField(default=False)),
                ('anything_else', models.TextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 264904))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 264904))),
                ('IsDelete', models.BooleanField(default=False)),
                ('ReferenceDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reference_check.referencedetails')),
            ],
        ),
    ]
