# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reference_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_check',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 983615)),
        ),
        migrations.AlterField(
            model_name='reference_check',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 983615)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 983615)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 42, 983615)),
        ),
    ]
