# Generated by Django 5.0.2 on 2025-01-10 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reference_check', '0003_referencedetails_ref1_candidate_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_check',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 3, 28, 506372)),
        ),
        migrations.AlterField(
            model_name='reference_check',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 3, 28, 506372)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 3, 28, 506372)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='Inteview_AssementID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 3, 28, 506372)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ref1_status',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ref2_status',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ref3_status',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
