# Generated by Django 5.0.2 on 2025-01-14 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reference_check', '0004_alter_reference_check_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_check',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 753299)),
        ),
        migrations.AlterField(
            model_name='reference_check',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 753299)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 744930)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='Inteview_AssementID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 15, 9, 52, 744930)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ref1_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ref2_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ref3_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
