# Generated by Django 5.0.2 on 2025-05-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reference_check', '0005_alter_reference_check_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_check',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 386309)),
        ),
        migrations.AlterField(
            model_name='reference_check',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 386309)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 380152)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 16, 2, 41, 380152)),
        ),
    ]
