# Generated by Django 5.0.2 on 2025-07-05 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reference_check', '0007_alter_reference_check_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_check',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 371453)),
        ),
        migrations.AlterField(
            model_name='reference_check',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 371453)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 371453)),
        ),
        migrations.AlterField(
            model_name='referencedetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 371453)),
        ),
    ]
