# Generated by Django 5.0.2 on 2024-10-09 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0003_attendancesalaryfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesalaryfile',
            name='PdfFileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancesalaryfile',
            name='PdfFileTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 308552)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 308552)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 308552)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 308552)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 308552)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 308552)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 288771)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 288771)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 315736)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 315736)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 307366)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 307366)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 298088)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 298088)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 314374)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 314374)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 311558)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 312509)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 315736)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 315736)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 314374)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 314374)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 315736)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 52, 33, 315736)),
        ),
    ]
