# Generated by Django 5.0.2 on 2025-01-07 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0006_alter_attendance_data_createddatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='Earned_Total_Allowance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 32, 34, 100615)),
        ),
    ]
