# Generated by Django 5.0.11 on 2025-01-27 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0009_alifcsvpunchrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 775799)),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 775811)),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='first_in_punch',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='last_out_punch',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='worked_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='working_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 776939)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 776952)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 777233)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 777244)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 777611)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 777622)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 775427)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 775440)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 780080)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 780094)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 776639)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 776654)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 776390)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 776403)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 779066)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 779077)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 778263)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 778275)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 779606)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 779659)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 778779)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 778793)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 779300)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 9, 8, 779312)),
        ),
    ]
