# Generated by Django 5.0.11 on 2025-01-29 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0010_alter_alifcsvpunchrecord_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 315183)),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 315205)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 316778)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='EmployeeCode',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='IsUpload',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 316797)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='Status',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 317220)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 317237)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 317613)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 317631)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 314522)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 314538)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 320994)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 321011)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 316344)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='Date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='EmployeeCode',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 316366)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='Status',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='Attendance_Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 315958)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='File_Name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 315979)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 319696)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 319722)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 318405)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 318417)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 320633)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 320656)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 319189)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 319208)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 320210)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 12, 10, 320230)),
        ),
    ]
