# Generated by Django 5.0.2 on 2025-07-05 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0015_alter_alifcsvpunchrecord_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='alifcsvpunchrecord',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='attendancesalaryfile',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='organization_details',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='payrollerrorlog',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='raw_attendance_data_file',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 326764)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='salaryemails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='shfitmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='update_attendance_request',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 329729)),
        ),
        migrations.AlterField(
            model_name='weekoffdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
