# Generated by Django 5.0.2 on 2025-09-15 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0021_alter_alifcsvpunchrecord_createddatetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlifCSVPunchRecord_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('emp_code', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=255)),
                ('punch_limit', models.IntegerField()),
                ('working_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('punch_date', models.DateField()),
                ('attend_code', models.CharField(max_length=5)),
                ('first_in_punch', models.TimeField(blank=True, null=True)),
                ('last_out_punch', models.TimeField(blank=True, null=True)),
                ('worked_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('opr_id', models.CharField(max_length=10)),
                ('opr_date', models.DateField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
