# Generated by Django 5.0.2 on 2025-09-19 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0022_alifcsvpunchrecord_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.BigIntegerField(db_index=True)),
                ('EmployeeCode', models.CharField(db_index=True, max_length=255)),
                ('Date', models.DateField(db_index=True)),
                ('In_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Out_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('S_In_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('S_Out_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Duty_Hour', models.CharField(blank=True, max_length=255, null=True)),
                ('Over_Time', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Late_Hour', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ActualStatus', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('LeaveID', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Remarks', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('From_Date', models.DateField(blank=True, null=True)),
                ('To_Date', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month_name', models.CharField(blank=True, max_length=255, null=True)),
                ('IsAdvancePosting', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('IsPresent', models.BooleanField(db_index=True, default=False)),
                ('HotelID', models.BigIntegerField(db_index=True, default=0)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ActionBy', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ActionByName', models.CharField(blank=True, max_length=255, null=True)),
                ('ActionDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
