# Generated by Django 5.0.2 on 2025-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0023_salaryattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryattendance',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryattendance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
