# Generated by Django 5.0.2 on 2025-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0025_payrollprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll_Bulk_Lock_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('inserted', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='salaryattendance',
            name='PresentValue',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
