# Generated by Django 5.0.2 on 2025-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0026_payroll_bulk_lock_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryattendance',
            name='PresentValue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
