# Generated by Django 5.0.2 on 2025-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0027_alter_salaryattendance_presentvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='Earned_CCA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='Earned_ConveyanceAllowance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='Earned_OtherAllowance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
