# Generated by Django 5.0.2 on 2025-10-08 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0028_salaryslip_earned_cca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Slip_V1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(max_length=255)),
                ('EmpID', models.BigIntegerField(blank=True, default=0, null=True)),
                ('Emp_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Desingation', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('DOB', models.CharField(blank=True, max_length=255, null=True)),
                ('DOJ', models.CharField(blank=True, max_length=255, null=True)),
                ('UAN_No', models.CharField(blank=True, max_length=255, null=True)),
                ('CTC', models.CharField(blank=True, max_length=255, null=True)),
                ('Gross_Salary_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Basic_Salary_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('HRA_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Conveyance_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('CCA_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Total', models.CharField(blank=True, max_length=255, null=True)),
                ('Actual_Attendance_Days', models.CharField(blank=True, max_length=255, null=True)),
                ('Basic_Salary_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('HRA_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('Conveyance_Earnedd', models.CharField(blank=True, max_length=255, null=True)),
                ('CCA_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('Arrers', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Earning', models.CharField(blank=True, max_length=255, null=True)),
                ('PF_Employee_Deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('PF_Employer_Deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('PT', models.CharField(blank=True, max_length=255, null=True)),
                ('Other_Deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('Net_Payble', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_no_Days_in_month', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_days', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_absent', models.CharField(blank=True, max_length=255, null=True)),
                ('IsGenerated', models.BooleanField(default=False)),
                ('HrVerify', models.BooleanField(default=False)),
                ('FcVerify', models.BooleanField(default=False)),
                ('IsLocked', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Earning_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True)),
                ('SalaryTitleID', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.CharField(blank=True, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('SalaryAttendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Payroll.salaryattendance')),
            ],
        ),
    ]
