# Generated by Django 5.0.2 on 2025-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0029_salary_slip_v1_salary_earning_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_earning_details',
            name='SalaryTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
