# Generated by Django 5.0.2 on 2025-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0030_salary_earning_details_salarytitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='Conveyance_Earnedd',
            new_name='Conveyance_Earned',
        ),
        migrations.AddField(
            model_name='salary_slip_v1',
            name='HotelID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
