# Generated by Django 5.0.2 on 2025-10-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0031_rename_conveyance_earnedd_salary_slip_v1_conveyance_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_earning_details',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
