# Generated by Django 5.0.2 on 2025-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0032_alter_salary_earning_details_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_slip_v1',
            name='Other_Allowance_Earned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
