# Generated by Django 5.0.2 on 2025-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0033_salary_slip_v1_other_allowance_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_slip_v1',
            name='Other_Allowance_Fixed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
