# Generated by Django 5.0.2 on 2025-10-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0034_salary_slip_v1_other_allowance_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_slip_v1',
            name='Total',
        ),
        migrations.AddField(
            model_name='salary_slip_v1',
            name='Total_Fixed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
