# Generated by Django 5.0.2 on 2025-10-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0035_remove_salary_slip_v1_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='no_of_absent',
            new_name='Absent_Days',
        ),
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='no_of_days',
            new_name='Present_Days',
        ),
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='total_no_Days_in_month',
            new_name='Total_No_Days_In_Month',
        ),
    ]
