# Generated by Django 5.0.2 on 2025-10-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0036_rename_no_of_absent_salary_slip_v1_absent_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary_Slip_V1',
        ),
    ]
