# Generated by Django 5.0.2 on 2025-10-11 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0037_delete_salary_slip_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Slip_V1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(max_length=255)),
                ('EmpID', models.BigIntegerField(blank=True, default=0, null=True)),
                ('Emp_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Desingation', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('DOJ', models.CharField(blank=True, max_length=255, null=True)),
                ('UAN_No', models.CharField(blank=True, max_length=255, null=True)),
                ('CTC', models.CharField(blank=True, max_length=255, null=True)),
                ('Gross_Salary_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Basic_Salary_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('HRA_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Conveyance_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('CCA_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Other_Allowance_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('Basic_Salary_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('HRA_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('Conveyance_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('CCA_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('Other_Allowance_Earned', models.CharField(blank=True, max_length=255, null=True)),
                ('Arrers', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Earning', models.CharField(blank=True, max_length=255, null=True)),
                ('PF_Employee_Deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('PF_Employer_Deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('PT', models.CharField(blank=True, max_length=255, null=True)),
                ('Other_Deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('Net_Payble', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_No_Days_In_Month', models.CharField(blank=True, max_length=255, null=True)),
                ('Present_Days', models.CharField(blank=True, max_length=255, null=True)),
                ('Absent_Days', models.CharField(blank=True, max_length=255, null=True)),
                ('IsGenerated', models.BooleanField(default=False)),
                ('HrVerify', models.BooleanField(default=False)),
                ('FcVerify', models.BooleanField(default=False)),
                ('IsLocked', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('Provident_Fund_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('ESIC_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Bank_Account_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Pay_Mode', models.CharField(blank=True, max_length=255, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Bank_IFSC_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Bank_Branch', models.CharField(blank=True, max_length=255, null=True)),
                ('HotelID', models.BigIntegerField(db_index=True, default=0)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
