# Generated by Django 5.0.2 on 2025-10-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0038_salary_slip_v1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary_Slip_V1',
        ),
    ]
