# Generated by Django 5.0.2 on 2025-10-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0040_salary_slip_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelock',
            name='IsGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
