# Generated by Django 5.0.2 on 2025-10-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0041_attendancelock_isgenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelock',
            name='EmpID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
