# Generated by Django 5.0.2 on 2025-10-12 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0042_attendancelock_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Deduction_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True)),
                ('SalaryTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('SalaryTitleID', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('SalaryAttendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Payroll.salaryattendance')),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Fixed_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True)),
                ('SalaryTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('SalaryTitleID', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('SalaryAttendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Payroll.salaryattendance')),
            ],
        ),
    ]
