# Generated by Django 5.0.2 on 2025-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0043_salary_deduction_details_salary_fixed_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_deduction_details',
            name='TitleOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary_deduction_details',
            name='TypeOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary_earning_details',
            name='TitleOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary_earning_details',
            name='TypeOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary_fixed_details',
            name='TitleOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary_fixed_details',
            name='TypeOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
