# Generated by Django 5.0.2 on 2025-10-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0044_salary_deduction_details_titleorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='UAN_No',
            new_name='Pan_No',
        ),
    ]
