# Generated by Django 5.0.2 on 2025-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0045_rename_uan_no_salary_slip_v1_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_slip_v1',
            name='EmpStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
