# Generated by Django 5.0.2 on 2025-10-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0046_salary_slip_v1_empstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='Desingation',
            new_name='Designation',
        ),
    ]
