# Generated by Django 5.0.2 on 2025-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0047_rename_desingation_salary_slip_v1_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='Net_Payble',
            new_name='Net_Payable',
        ),
        migrations.AddField(
            model_name='salary_slip_v1',
            name='Net_Payable_In_Words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
