# Generated by Django 5.0.2 on 2025-10-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0048_rename_net_payble_salary_slip_v1_net_payable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='AdvanceLoan',
            new_name='Advance_Loan',
        ),
    ]
