# Generated by Django 5.0.2 on 2025-10-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0049_rename_advanceloan_salary_slip_v1_advance_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_slip_v1',
            old_name='TaxDeduction',
            new_name='Tax_Deduction',
        ),
    ]
