# Generated by Django 5.0.2 on 2025-10-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0050_rename_taxdeduction_salary_slip_v1_tax_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelock',
            name='IsAttendanceMoved',
            field=models.BooleanField(default=False),
        ),
    ]
