# Generated by Django 5.0.2 on 2025-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0051_attendancelock_isattendancemoved'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryattendance',
            name='IsAttendanceMoved',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
