# Generated by Django 5.0.2 on 2025-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0052_salaryattendance_isattendancemoved'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelock',
            name='IsFC_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelock',
            name='IsHR_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
