# Generated by Django 5.0.2 on 2025-11-04 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0053_attendancelock_isfc_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response_Data_Generate_Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Year', models.CharField(blank=True, max_length=255, null=True)),
                ('Emp_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Emp_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Response_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Response_Message', models.CharField(blank=True, max_length=255, null=True)),
                ('Hotel_Id', models.BigIntegerField(db_index=True, default=0)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
