# Generated by Django 5.0.2 on 2025-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0054_response_data_generate_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_data_generate_slip',
            name='Emp_ID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
