# Generated by Django 5.0.2 on 2025-11-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0055_response_data_generate_slip_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryattendance',
            name='IsAttendanceModified',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
