# Generated by Django 5.0.2 on 2025-11-13 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0056_salaryattendance_isattendancemodified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Attendance_Request_V1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Apporve_status', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('SalaryAttendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Payroll.salaryattendance')),
            ],
        ),
    ]
