# Generated by Django 5.0.2 on 2025-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0058_salary_company_contribution_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_slip_v1',
            name='Total_Company_Contribution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
