# Generated by Django 5.0.2 on 2025-11-19 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0059_salary_slip_v1_total_company_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Data_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(db_index=True, max_length=255)),
                ('Date', models.DateField(db_index=True)),
                ('In_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Out_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('S_In_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('S_Out_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Duty_Hour', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('IsUpload', models.BooleanField(db_index=True, default=False)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('ActionBy', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ActionByName', models.CharField(blank=True, max_length=255, null=True)),
                ('ActionDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
