# Generated by Django 5.0.2 on 2025-12-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0060_attendance_data_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_earning_details',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary_earning_details',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary_company_contribution_details',
            name='Amount',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='salary_deduction_details',
            name='Amount',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='salary_earning_details',
            name='Amount',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='salary_earning_details',
            name='Date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary_fixed_details',
            name='Amount',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30),
        ),
    ]
