# Generated by Django 5.0.2 on 2025-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0061_salary_earning_details_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_earning_details',
            name='SalaryAttendance',
        ),
    ]
