# Generated by Django 5.0.2 on 2025-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0062_remove_salary_earning_details_salaryattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_earning_details',
            name='EmpID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
