# Generated by Django 5.0.2 on 2025-12-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0063_salary_earning_details_empid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_earning_details',
            name='EmpCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
