# Generated by Django 5.0.2 on 2025-12-16 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0064_salary_earning_details_empcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_Attendance_Upload_Punch_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(db_index=True, max_length=255)),
                ('Date', models.DateField(db_index=True)),
                ('In_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Out_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Duty_Hour', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('LeaveID', models.CharField(blank=True, db_index=True, default=0, max_length=255, null=True)),
                ('IsUpload', models.BooleanField(db_index=True, default=False)),
                ('IsAttendanceModified', models.BooleanField(db_index=True, default=False)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Excel_Attendance_Upload_Punch_Record_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(db_index=True, max_length=255)),
                ('Date', models.DateField(db_index=True)),
                ('In_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Out_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Duty_Hour', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('LeaveID', models.CharField(blank=True, db_index=True, default=0, max_length=255, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
