# Generated by Django 5.0.2 on 2025-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0065_excel_attendance_upload_punch_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_slip_v1',
            name='Bonus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
