# Generated by Django 5.0.2 on 2025-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0066_salary_slip_v1_bonus_salaryattendance_isupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_data',
            name='EmpID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        )
    ]
