# Generated by Django 5.0.2 on 2026-01-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0067_attendance_data_empid_salaryattendance_isupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_data',
            name='IsUpload_Biometric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance_data',
            name='IsUpload_WeekOff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance_data',
            name='Is_WeekOff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance_data',
            name='LeaveID',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
