# Generated by Django 5.0.2 on 2026-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0068_attendance_data_isupload_biometric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_data',
            name='Is_Leave',
            field=models.BooleanField(default=False),
        ),
    ]
