# Generated by Django 5.0.2 on 2026-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0069_attendance_data_is_leave_salaryattendance_isupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_attendance_upload_punch_record',
            name='IsUpload_Biometric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excel_attendance_upload_punch_record',
            name='Is_Leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excel_attendance_upload_punch_record_log',
            name='IsUpload_Biometric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excel_attendance_upload_punch_record_log',
            name='Is_Leave',
            field=models.BooleanField(default=False),
        ),
    ]
