# Generated by Django 5.0.2 on 2026-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0070_excel_attendance_upload_punch_record_isupload_biometric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_attendance_upload_punch_record',
            name='IsUpload_Biometric',
        ),
        migrations.RemoveField(
            model_name='excel_attendance_upload_punch_record',
            name='Is_Leave',
        ),
        migrations.RemoveField(
            model_name='excel_attendance_upload_punch_record_log',
            name='IsUpload_Biometric',
        ),
        migrations.RemoveField(
            model_name='excel_attendance_upload_punch_record_log',
            name='Is_Leave',
        ),
    ]
