# Generated by Django 5.0.2 on 2026-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Payroll', '0071_remove_excel_attendance_upload_punch_record_isupload_biometric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_data',
            name='IsUpload_Biometric',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='IsUpload_WeekOff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='Is_Leave',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_data',
            name='Is_WeekOff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
