# Generated by Django 4.1.7 on 2023-03-25 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casual_Manpower_Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Prepared_By', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Numbers_Required', models.CharField(max_length=100)),
                ('Reason', models.TextField(blank=True, max_length=100)),
                ('Function', models.CharField(blank=True, max_length=100)),
                ('Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('No_Of_Pax', models.CharField(blank=True, max_length=100)),
                ('Date_Required', models.DateField()),
                ('Est_Sales_Volume', models.CharField(blank=True, max_length=100)),
                ('Reporting_Time', models.TimeField(blank=True)),
            ],
        ),
    ]
