# Generated by Django 4.1.7 on 2023-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casualmanpower', '0002_casual_manpower_requisition_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casual_manpower_requisition',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
