# Generated by Django 5.0.2 on 2024-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casualmanpower', '0003_casual_manpower_requisition_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casual_manpower_requisition',
            name='Date_Required',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='casual_manpower_requisition',
            name='Est_Sales_Volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casual_manpower_requisition',
            name='Function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casual_manpower_requisition',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='casual_manpower_requisition',
            name='Reporting_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
