# Generated by Django 4.1.8 on 2024-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetterSalaryIncrement', '0002_alter_letterofsalaryincreamentemployeedetail_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofsalaryincreamentemployeedetail',
            name='CTC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
