# Generated by Django 5.0.2 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetterSalaryIncrement', '0005_remove_letterofsalaryincreamentemployeedetail_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofsalaryincreamentemployeedetail',
            name='Issuing_designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofsalaryincreamentemployeedetail',
            name='Issuing_manager_name',
            field=models.CharField(max_length=255),
        ),
    ]
