# Generated by Django 5.0.2 on 2025-03-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0002_rename_amcmode_amc_entry_master_amctype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amc_entry_master',
            old_name='Status',
            new_name='Final_Status',
        ),
    ]
