# Generated by Django 5.0.2 on 2025-03-29 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0005_alter_amc_entry_master_amctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalliaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryDate', models.DateField(blank=True, null=True)),
                ('GuestName', models.CharField(max_length=255)),
                ('PropertyName', models.CharField(max_length=255)),
                ('RoomNo', models.IntegerField(blank=True, null=True)),
                ('Month', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckInDate', models.DateField(blank=True, null=True)),
                ('CheckOutDate', models.DateField(blank=True, null=True)),
                ('ResponseDate', models.DateField(blank=True, null=True)),
                ('CheckInProcess', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('WorkingOrder', models.CharField(blank=True, max_length=10, null=True)),
                ('Cleanliness', models.CharField(blank=True, max_length=10, null=True)),
                ('CustomerService', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ConditionOfHotel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('BreakfastExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('WohProgramExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('SpaExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('NPS', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('StaffHelpfulness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('DeliveryHkServices', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('StaffResponsiveness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('WohAppExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OverallFnbExperience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PropertyAnticipatedGuestNeeds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('LpMemberSatisfaction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviewer', models.CharField(max_length=255)),
                ('EntryDate', models.DateField(blank=True, null=True)),
                ('Month', models.CharField(blank=True, max_length=255, null=True)),
                ('ReviewRating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Classification', models.CharField(blank=True, max_length=50, null=True)),
                ('Location', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('LocationScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Room', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('RoomScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Cleanliness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('CleanlinessScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('GriTM', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PublishedDate', models.DateField()),
                ('RatingScale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ValueScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Gastronomy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('GastronomyScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Service', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ServiceScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Source', models.CharField(blank=True, max_length=255, null=True)),
                ('ReviewScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('DepartmentRatingScale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ReviewTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('ReviewText', models.TextField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
