# Generated by Django 5.0.2 on 2025-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMC_Renewal', '0009_delete_vendordetails_amc_entry_master_vendoraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc_entry_master',
            name='VendorPincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
