# Generated by Django 5.0.2 on 2025-12-03 09:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy_Data_Privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy_data_privacy_editor',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
