# Generated by Django 5.0.2 on 2025-12-03 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policy_Data_Privacy', '0002_alter_policy_data_privacy_editor_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='HotelID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data_privacy_deleted_file_of_employee',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data_privacy_deleted_file_of_employee',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data_privacy_employee_detail',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data_privacy_employee_detail',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letter_of_data_privacyexperience',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='letter_of_data_privacyexperience',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='policy_data_privacy_editor',
            name='content',
            field=models.TextField(),
        ),
    ]
