# Generated by Django 5.0.2 on 2025-12-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy_Data_Privacy', '0003_policy_data_privacy_editor_createdby_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letter_Of_Data_PrivacyExperience',
        ),
    ]
