# Generated by Django 5.0.2 on 2025-12-03 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policy_Data_Privacy', '0004_delete_letter_of_data_privacyexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter_Data_Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(blank=True, max_length=255, null=True)),
                ('Module_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('HotelID', models.BigIntegerField(default=0)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='data_privacy_deleted_file_of_employee',
            name='HotelID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data_privacy_employee_detail',
            name='HotelID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data_privacy_employee_detail',
            name='generate_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policy_data_privacy_editor',
            name='Letter_Data_Item_Master',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Policy_Data_Privacy.letter_data_item_master'),
            preserve_default=False,
        ),
    ]
