# Generated by Django 5.0.2 on 2025-12-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy_Data_Privacy', '0005_letter_data_item_master_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policy_Data_Privacy_Editor',
            new_name='Letter_Editor',
        ),
    ]
