# Generated by Django 5.0.2 on 2025-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniformInventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniforminformation',
            name='EmpID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
