# Generated by Django 5.0.2 on 2025-11-24 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniformInventory', '0002_uniforminformation_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniforminformation',
            name='IssuedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
