# Generated by Django 5.0.2 on 2025-11-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniformInventory', '0003_uniforminformation_issueddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniforminformation',
            name='HR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniforminformation',
            name='HRCreatedBy',
            field=models.BigIntegerField(default=0),
        ),
    ]
