# Generated by Django 5.0.2 on 2024-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hiring_data_NEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_division', models.CharField(max_length=100)),
                ('positions1', models.CharField(max_length=100)),
                ('positions2', models.CharField(max_length=100)),
                ('positions3', models.CharField(max_length=100)),
                ('positions4', models.CharField(max_length=100)),
                ('reporting', models.TextField()),
                ('Feedback_percent1', models.TextField()),
                ('Feedback_percent2', models.TextField()),
                ('Feedback_percent3', models.TextField()),
                ('Feedback_percent4', models.TextField()),
                ('Feedback_position1', models.TextField()),
                ('Feedback_position2', models.TextField()),
                ('Feedback_position3', models.TextField()),
                ('Feedback_position4', models.TextField()),
                ('hiring', models.TextField()),
                ('fairing', models.TextField()),
                ('property_transfer', models.TextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(auto_now_add=True)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
