# Generated by Django 5.0.2 on 2024-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiring_Reporting_Performance_Review_Guidelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_percent1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_percent2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_percent3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_percent4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_position1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_position2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_position3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='Feedback_position4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='department_division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='fairing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='hiring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='positions1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='positions2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='positions3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='positions4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='property_transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiring_data_new',
            name='reporting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
