# Generated by Django 5.0.11 on 2025-01-28 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0002_alter_entry_master_date_joined_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apadp',
            name='Finalcomments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 1, 28)),
        ),
    ]
