# Generated by Django 5.0.11 on 2025-01-31 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0003_alter_apadp_finalcomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 1, 31)),
        ),
        migrations.AlterField(
            model_name='finalperformancerating',
            name='JustificationPromotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalperformancerating',
            name='JustificationSalaryCorrection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
