# Generated by Django 5.0.2 on 2025-05-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0004_alter_entry_master_date_joined_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 5, 17)),
        ),
    ]
