# Generated by Django 5.0.2 on 2025-07-28 12:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0006_alter_entry_master_date_joined_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadp',
            name='Last_Action_By_EmpCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Last_Action_By_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Last_CEO_Action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Last_CEO_action_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Last_CEO_action_Remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Pending_From_Emp_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Pending_From_Emp_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 7, 28)),
        ),
        migrations.CreateModel(
            name='Entry_Master_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastApporvalStatus', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('hr_as', models.CharField(blank=True, max_length=255, null=True)),
                ('ep_as', models.CharField(blank=True, max_length=255, null=True)),
                ('ar_as', models.CharField(blank=True, max_length=255, null=True)),
                ('rd_as', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_as', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_as_remarks', models.TextField(blank=True, null=True)),
                ('hr_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('ep_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('ar_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('rd_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('hr_ar_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('ceo_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedByUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(auto_now_add=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Entry_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PADP.entry_master')),
            ],
        ),
    ]
