# Generated by Django 5.0.2 on 2025-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0007_apadp_last_action_by_empcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APADP_Master_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastApporvalStatus', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('hr_as', models.CharField(blank=True, max_length=255, null=True)),
                ('ar_as', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_as', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_as_remarks', models.TextField(blank=True, null=True)),
                ('hr_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('ar_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('hr_ar_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('ceo_actionOnDatetime', models.DateTimeField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(auto_now_add=True)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
