# Generated by Django 5.0.2 on 2025-07-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0008_apadp_master_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadp_master_log',
            name='APADP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PADP.apadp'),
        ),
    ]
