# Generated by Django 5.0.2 on 2025-07-29 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0009_apadp_master_log_apadp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_master_log',
            name='Entry_Master',
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Last_Action_By_EmpCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Last_Action_By_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Last_CEO_Action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Last_CEO_action_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Last_CEO_action_Remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Pending_From_Emp_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='Pending_From_Emp_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 7, 29)),
        ),
        migrations.DeleteModel(
            name='APADP_Master_Log',
        ),
        migrations.DeleteModel(
            name='Entry_Master_Log',
        ),
    ]
