# Generated by Django 5.0.2 on 2025-07-30 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0011_apadp_master_log_entry_master_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate_Level_Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleCode', models.CharField(max_length=100)),
                ('StageName', models.CharField(max_length=255)),
                ('SequenceOrder', models.IntegerField()),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 7, 30)),
        ),
    ]
