# Generated by Django 5.0.2 on 2025-07-31 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0012_associate_level_stage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Associate_Level_Stage',
        ),
        migrations.AddField(
            model_name='apadp',
            name='AuditedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apadp',
            name='AuditedBy_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 7, 31)),
        ),
    ]
