# Generated by Django 5.0.2 on 2025-07-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0013_delete_associate_level_stage_apadp_auditedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_master',
            old_name='Pending_From_Emp_Code',
            new_name='AuditedBy_Name',
        ),
        migrations.RemoveField(
            model_name='apadp',
            name='Pending_From_Emp_Code',
        ),
        migrations.RemoveField(
            model_name='apadp',
            name='Pending_From_Emp_Name',
        ),
        migrations.RemoveField(
            model_name='entry_master',
            name='Pending_From_Emp_Name',
        ),
        migrations.AddField(
            model_name='entry_master',
            name='AuditedBy',
            field=models.BigIntegerField(default=0),
        ),
    ]
