# Generated by Django 5.0.2 on 2025-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0014_rename_pending_from_emp_code_entry_master_auditedby_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadp',
            name='CreatedByUsername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
