# Generated by Django 5.0.2 on 2025-08-01 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0015_apadp_createdbyusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadp',
            name='DraftBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='DraftByDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='DraftByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='HR_Manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apadp',
            name='Reporting_To_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='DraftBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='DraftByDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='DraftByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry_master',
            name='HR_Manager_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 8, 1)),
        ),
    ]
