# Generated by Django 5.0.2 on 2025-08-25 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0016_apadp_draftby_apadp_draftbydatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_master',
            name='DottedLine_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry_master',
            name='Date_Joined_Company',
            field=models.DateField(default=datetime.date(2025, 8, 25)),
        ),
    ]
