# Generated by Django 5.0.2 on 2025-11-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0018_entry_master_current_salary_alter_apadp_auditedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadp',
            name='Current_Salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
