# Generated by Django 5.0.2 on 2025-12-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PADP', '0019_apadp_current_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_master',
            name='Department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
