# Generated by Django 4.1.8 on 2023-12-14 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Source_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_source_category', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entry_Master_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryYear', models.IntegerField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Finance_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance_category', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Market_Segment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_segment_category', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Market_Segment_Entry_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
                ('Market_Segment_Category_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.market_segment_category')),
            ],
        ),
        migrations.CreateModel(
            name='Finance_Category_Entry_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
                ('Finance_Category_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.finance_category')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Source_Entry_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Business_Source_Category_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.business_source_category')),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
            ],
        ),
    ]
