# Generated by Django 5.0.2 on 2024-04-13 05:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YearlyBudget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostPerCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CostPerOccupiedRoomNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpensesIncludingPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CostPerCoverEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CostPerCover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.costpercover')),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
            ],
        ),
        migrations.CreateModel(
            name='CostPerOccupiedRoomNightEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CostPerOccupiedRoomNight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.costperoccupiedroomnight')),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesIncludingPayrollEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
                ('ExpensesIncludingPayroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.expensesincludingpayroll')),
            ],
        ),
    ]
