# Generated by Django 5.0.2 on 2025-08-18 11:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YearlyBudget', '0002_costpercover_costperoccupiedroomnight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Engineering_category', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Engineering_Category_Entry_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_1', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_3', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_4', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_5', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_6', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_7', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_8', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_9', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_10', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_11', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Month_12', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Engineering_Category_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.engineering_category')),
                ('EntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YearlyBudget.entry_master_year')),
            ],
        ),
    ]
