# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Approvel_Templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_deta',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='contract_deta',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='contract_summary',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138074)),
        ),
        migrations.AlterField(
            model_name='contract_summary',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138074)),
        ),
        migrations.AlterField(
            model_name='opportunityss',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 131739)),
        ),
        migrations.AlterField(
            model_name='opportunityss',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 131739)),
        ),
        migrations.AlterField(
            model_name='owner_deta',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='owner_deta',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='owners',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138074)),
        ),
        migrations.AlterField(
            model_name='owners',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138074)),
        ),
        migrations.AlterField(
            model_name='project',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='project',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='project_approvel_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 131739)),
        ),
        migrations.AlterField(
            model_name='project_approvel_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 131739)),
        ),
        migrations.AlterField(
            model_name='project_approvel_request',
            name='Opening_Date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 131739)),
        ),
        migrations.AlterField(
            model_name='project_deta',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
        migrations.AlterField(
            model_name='project_deta',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 12, 14, 19, 138581)),
        ),
    ]
