# Generated by Django 5.0.2 on 2025-07-05 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Approvel_Templates', '0006_alter_contract_deta_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_deta',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='contract_deta',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='contract_summary',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='contract_summary',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='opportunityss',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='opportunityss',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='owner_deta',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='owner_deta',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='owners',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='owners',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project_approvel_request',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project_approvel_request',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project_approvel_request',
            name='Opening_Date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project_deta',
            name='CreatedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
        migrations.AlterField(
            model_name='project_deta',
            name='ModifyDateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 10, 11, 25, 331731)),
        ),
    ]
