# Generated by Django 5.0.2 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpTermination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empterminationmodel',
            name='reviewed_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empterminationmodel',
            name='reviewed_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empterminationmodel',
            name='IsWarningIssued',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='empterminationmodel',
            name='LastWarningLatter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
