# Generated by Django 5.0.2 on 2025-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpTermination', '0002_empterminationmodel_reviewed_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empterminationmodel',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
