# Generated by Django 4.1.7 on 2023-03-31 06:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_order_form',
            name='CreatedBy',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake_order_form',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cake_order_form',
            name='ModifyBy',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake_order_form',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cake_order_form',
            name='OrganizationID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
