# Generated by Django 4.1.7 on 2023-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_order_form',
            name='Required_Time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cake_order_form',
            name='Time',
            field=models.CharField(max_length=20),
        ),
    ]
