# Generated by Django 4.1.7 on 2023-03-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cake_order_form_required_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_order_form',
            name='Required_Time',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cake_order_form',
            name='Time',
            field=models.TimeField(max_length=20),
        ),
    ]
