# Generated by Django 4.1.7 on 2023-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cake_order_form_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_order_form',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cake_order_form',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
    ]
