# Generated by Django 4.1.7 on 2023-04-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cake_order_form_required_time_and_more'),
        ('app', '0004_alter_cake_order_form_createdby_and_more'),
    ]

    operations = [
    ]
