# Generated by Django 4.1.8 on 2023-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20230404_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthListMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthName', models.CharField(max_length=20)),
            ],
        ),
    ]
