# Generated by Django 4.1.8 on 2023-10-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_monthlistmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.BigIntegerField()),
                ('Organization_name', models.CharField(max_length=250)),
                ('OrganizationLogo', models.CharField(max_length=250)),
                ('ShortDisplayLabel', models.CharField(max_length=250)),
                ('OrganizationDomainCode', models.CharField(max_length=250)),
            ],
        ),
    ]
