# Generated by Django 4.1.8 on 2023-12-22 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_organizationmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmaster',
            name='Organization_name',
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='Activation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='CreatedBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='FinancialYearStart',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='GSTNumber',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='IsNileHotel',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='MComLogo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='ModifyBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='organizationmaster',
            name='OrganizationName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='OrganizationDomainCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='OrganizationLogo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='ShortDisplayLabel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
