# Generated by Django 4.1.8 on 2023-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_organizationmaster_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmaster',
            name='OrganizationName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
