# Generated by Django 5.0.2 on 2024-03-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_departmentmaster_designationmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmaster',
            name='FinancialYearStart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
