# Generated by Django 5.0.2 on 2024-05-30 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_organizationmaster_financialyearstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(blank=True, max_length=250, null=True)),
                ('EmpName', models.CharField(blank=True, max_length=250, null=True)),
                ('Department', models.CharField(blank=True, max_length=250, null=True)),
                ('Designation', models.CharField(blank=True, max_length=250, null=True)),
                ('DateofJoining', models.DateField(blank=True, null=True)),
                ('ReportingtoDesigantion', models.CharField(blank=True, max_length=250, null=True)),
                ('ReportingtoLevel', models.CharField(blank=True, max_length=250, null=True)),
                ('Level', models.CharField(blank=True, max_length=250, null=True)),
                ('EmpStatus', models.CharField(blank=True, max_length=250, null=True)),
                ('Gender', models.CharField(blank=True, max_length=250, null=True)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
