# Generated by Django 5.0.2 on 2024-06-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_employeemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='BloodGroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='EmailMailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='EmergencyContact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='EmpPhoto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='OfficalMailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
