# Generated by Django 5.0.2 on 2024-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_employeemaster_bloodgroup_employeemaster_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmaster',
            name='ReviewSoftware',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
