# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_organizationmaster_reviewsoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Location_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Village', models.CharField(blank=True, max_length=255, null=True)),
                ('OfficeName', models.CharField(blank=True, max_length=255, null=True)),
                ('PinCode', models.CharField(blank=True, max_length=255, null=True)),
                ('SubDistName', models.CharField(blank=True, max_length=255, null=True)),
                ('DistrictName', models.CharField(blank=True, max_length=255, null=True)),
                ('StateName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumanResourcesEmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(blank=True, max_length=250, null=True)),
                ('EmpName', models.CharField(blank=True, max_length=250, null=True)),
                ('Department', models.CharField(blank=True, max_length=250, null=True)),
                ('Designation', models.CharField(blank=True, max_length=250, null=True)),
                ('DateofJoining', models.DateField(blank=True, null=True)),
                ('ReportingtoDesigantion', models.CharField(blank=True, max_length=250, null=True)),
                ('ReportingtoLevel', models.CharField(blank=True, max_length=250, null=True)),
                ('Level', models.CharField(blank=True, max_length=250, null=True)),
                ('EmpStatus', models.CharField(blank=True, max_length=250, null=True)),
                ('Gender', models.CharField(blank=True, max_length=250, null=True)),
                ('OfficalMailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('EmailMailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('EmpPhoto', models.CharField(blank=True, max_length=500, null=True)),
                ('DottedLine', models.CharField(blank=True, max_length=250, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('BloodGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('EmergencyContact', models.CharField(blank=True, max_length=255, null=True)),
                ('Salary', models.BigIntegerField(blank=True, null=True)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEmailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_host', models.CharField(default='smtp.office365.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModuleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Report_title', models.CharField(blank=True, max_length=255, null=True)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('auth_token', models.CharField(max_length=255)),
                ('session_key', models.CharField(max_length=255)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_code', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_logo', models.URLField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
