# Generated by Django 5.0.2 on 2025-01-14 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_city_location_master_humanresourcesemployeemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappSmsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('template_id', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=20)),
                ('webHookDNId', models.CharField(max_length=20)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
