# Generated by Django 5.0.2 on 2025-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_whatsappsmsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='auth_token',
            field=models.CharField(max_length=755),
        ),
    ]
