# Generated by Django 5.0.11 on 2025-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_microsoftcredentialsmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='auth_token',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
