# Generated by Django 5.0.2 on 2025-09-11 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usersession_auth_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleUserRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(blank=True, max_length=250, null=True)),
                ('Module_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Is_Access', models.BooleanField(default=False)),
                ('Is_Full_Access', models.BooleanField(default=False)),
                ('OrganizationID', models.BigIntegerField()),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.datetime(2025, 9, 11, 13, 15, 39, 116321, tzinfo=datetime.timezone.utc))),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.datetime(2025, 9, 11, 13, 15, 39, 116321, tzinfo=datetime.timezone.utc))),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
