# Generated by Django 5.0.2 on 2025-09-12 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_moduleuserrights'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleuserrights',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='division_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moduleuserrights',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 23, 8, 149530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='moduleuserrights',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 23, 8, 149530, tzinfo=datetime.timezone.utc)),
        ),
    ]
