# Generated by Django 5.0.2 on 2025-09-12 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_moduleuserrights_isactive_usersession_division_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_order_form',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cake_order_form',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='designationmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='designationmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='humanresourcesemployeemaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='humanresourcesemployeemaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='microsoftcredentialsmail',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='microsoftcredentialsmail',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='moduleuserrights',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='moduleuserrights',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='organizationemailmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='organizationemailmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 468147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='whatsappsmsconfig',
            name='CreatedDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='whatsappsmsconfig',
            name='ModifyDateTime',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 7, 24, 33, 473744, tzinfo=datetime.timezone.utc)),
        ),
    ]
