# Generated by Django 5.0.2 on 2025-09-19 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_usersession_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='IsSecondary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cake_order_form',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cake_order_form',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='designationmaster',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='designationmaster',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='humanresourcesemployeemaster',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='humanresourcesemployeemaster',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='microsoftcredentialsmail',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='microsoftcredentialsmail',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moduleuserrights',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moduleuserrights',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationemailmaster',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationemailmaster',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='whatsappsmsconfig',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='whatsappsmsconfig',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
