# Generated by Django 5.0.2 on 2025-09-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_employeemaster_issecondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='Division',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
