# Generated by Django 5.0.2 on 2025-09-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_employeemaster_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='EmpID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
