# Generated by Django 5.0.2 on 2025-10-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_employeemaster_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmaster',
            name='Career_Share_Logo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
