# Generated by Django 4.1.7 on 2023-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Group_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(max_length=100)),
                ('Is_Visible', models.BooleanField(default=True)),
                ('Is_Enable', models.BooleanField(default=True)),
                ('Sort_Order', models.CharField(max_length=100)),
                ('Organization_Id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Domain_URL', models.CharField(max_length=100)),
                ('ProductLabel', models.CharField(max_length=100)),
                ('Is_Visible', models.BooleanField(default=True)),
                ('Is_Enable', models.BooleanField(default=True)),
                ('Organization_Id', models.BigIntegerField(default=0)),
                ('Sort_Order', models.CharField(max_length=100)),
                ('Parent_Id', models.BigIntegerField(default=0)),
                ('Is_Carporate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Group_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Group_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product_group_master')),
                ('Product_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product_master')),
            ],
        ),
    ]
