# Generated by Django 5.0.2 on 2025-09-26 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(blank=True, max_length=255, null=True)),
                ('HotelID', models.BigIntegerField(db_index=True, default=0)),
                ('date', models.DateField()),
                ('ta_ranking', models.IntegerField(blank=True, default=0, null=True)),
                ('ta_nrr', models.FloatField(blank=True, default=0, null=True)),
                ('google_ranking', models.IntegerField(blank=True, default=0, null=True)),
                ('google_nrr', models.FloatField(blank=True, default=0, null=True)),
                ('mmt_ranking', models.IntegerField(blank=True, default=0, null=True)),
                ('mmt_nrr', models.FloatField(blank=True, default=0, null=True)),
                ('booking_ranking', models.IntegerField(blank=True, default=0, null=True)),
                ('booking_nrr', models.FloatField(blank=True, default=0, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['date', 'HotelID'],
                'unique_together': {('HotelID', 'date')},
            },
        ),
    ]
