# Generated by Django 5.0.2 on 2025-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranking_Board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_ranking',
            name='booking_nrr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='booking_ranking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='google_nrr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='google_ranking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='mmt_nrr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='mmt_ranking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='ta_nrr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_ranking',
            name='ta_ranking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
