# Generated by Django 5.0.2 on 2025-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranking_Board', '0003_alter_hotel_ranking_booking_nrr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_ranking',
            name='ModifyDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
