# Generated by Django 5.0.2 on 2025-01-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessageDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.TextField(blank=True, null=True)),
                ('EmailMessageBody', models.TextField(blank=True, null=True)),
                ('AppTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('AppBody', models.TextField(blank=True, null=True)),
                ('AppUserID', models.TextField(blank=True, null=True)),
                ('DashboardTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('DashboardBody', models.TextField(blank=True, null=True)),
                ('DashboardUserID', models.TextField(blank=True, null=True)),
                ('DashboardIsView', models.BooleanField(default=False)),
                ('RetrunUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
