# Generated by Django 4.1.7 on 2023-04-05 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Parcel_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Of_Article', models.CharField(max_length=100)),
                ('Room_No', models.IntegerField(max_length=100)),
                ('Guest_Name', models.CharField(max_length=100)),
                ('Date_Of_Arrival', models.DateField(default=datetime.date.today)),
                ('Received_From', models.CharField(max_length=100)),
                ('Contact_No', models.CharField(max_length=12)),
                ('Received_By', models.CharField(max_length=100)),
                ('Date_Of_Delivery', models.DateField(default=datetime.date.today)),
                ('Given_By', models.CharField(max_length=100)),
                ('Handed_Over_To', models.CharField(max_length=100)),
                ('Remarks', models.TextField()),
            ],
        ),
    ]
