# Generated by Django 4.1.7 on 2023-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelregister', '0002_message_parcel_register_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_parcel_register',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
