# Generated by Django 4.1.8 on 2023-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesEventCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleseventcalendar',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
