# Generated by Django 4.1.8 on 2023-11-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='emp_code',
            field=models.CharField(max_length=200),
        ),
    ]
