# Generated by Django 4.1.8 on 2024-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0002_alter_loaletterofappointmentemployeedetail_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='Reporting_to_designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('T', 'T'), ('E', 'E'), ('M', 'M'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('M6', 'M6')], default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('T', 'T'), ('E', 'E'), ('M', 'M'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('M6', 'M6')], default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='mobile_number',
            field=models.CharField(max_length=250),
        ),
    ]
