# Generated by Django 5.0.2 on 2025-01-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0003_loaletterofappointmentemployeedetail_reporting_to_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='data',
        ),
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='general_manager_name',
        ),
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='hr_manager_name',
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='Hr_Designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='Hr_Name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='Issuing_designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='Issuing_manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='prefix',
            field=models.CharField(max_length=20),
        ),
    ]
