# Generated by Django 5.0.2 on 2025-01-14 09:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0004_remove_loaletterofappointmentemployeedetail_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='data',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='general_manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='hr_manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='Hr_Designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='Hr_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='Issuing_designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='Issuing_manager_name',
            field=models.CharField(max_length=255),
        ),
    ]
