# Generated by Django 5.0.2 on 2025-05-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0005_loaletterofappointmentemployeedetail_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='data',
        ),
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='general_manager_name',
        ),
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='loaletterofappointmentemployeedetail',
            name='hr_manager_name',
        ),
    ]
