# Generated by Django 5.0.2 on 2025-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0007_loaletterofappointmentemployeedetail_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='FinalHTML',
            field=models.TextField(blank=True, null=True),
        ),
    ]
