# Generated by Django 5.0.2 on 2025-12-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0009_letter_of_appointment_salary_detail_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letter_Of_Appointment_Salary_Detail_Master',
        ),
    ]
