# Generated by Django 5.0.2 on 2025-12-05 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0018_salary_detail_master_salary_title_old_id'),
        ('LETTEROFAPPOINTMENT', '0010_delete_letter_of_appointment_salary_detail_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter_Of_Appointment_Salary_Detail_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.BigIntegerField(db_index=True)),
                ('Permonth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Perannum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Salary_title_Old_Id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
                ('Effective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HumanResources.salary_details_effective')),
                ('Salary_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.salarytitle_master')),
            ],
        ),
    ]
