# Generated by Django 5.0.2 on 2025-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0011_letter_of_appointment_salary_detail_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='EmpID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
