# Generated by Django 5.0.2 on 2025-12-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0012_loaletterofappointmentemployeedetail_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='EmpID',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
