# Generated by Django 5.0.2 on 2025-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0013_alter_loaletterofappointmentemployeedetail_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='IsSaved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
