# Generated by Django 5.0.2 on 2025-12-20 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LETTEROFAPPOINTMENT', '0014_loaletterofappointmentemployeedetail_issaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaletterofappointmentemployeedetail',
            name='IsChecklist_Created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='DEPT',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='DEPTCreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='DEPTCreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='FNB',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='FNBCreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='FNBCreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='Finance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='FinanceCreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='FinanceCreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='HK',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='HKCreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='HKCreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='HR',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='HRCreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='HRCreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='IT',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='ITCreatedBy',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loaletterofappointmentemployeedetail',
            name='ITCreatedDateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
