# Generated by Django 5.0.2 on 2025-01-03 06:44

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevealingLetterEmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_joining', models.DateField()),
                ('date_of_Revealing', models.DateField(blank=True, null=True)),
                ('date_of_last_working', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('Reporting_to_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(max_length=200)),
                ('basic_salary', models.IntegerField()),
                ('address', models.TextField()),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('Hr_Name', models.CharField(max_length=255)),
                ('Hr_Designation', models.CharField(max_length=255)),
                ('Issuing_manager_name', models.CharField(max_length=255)),
                ('Issuing_designation', models.CharField(max_length=255)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RevealingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', ckeditor.fields.RichTextField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevealingLetterDeletedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('RevealingLetterEmployeeDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RevealingLetter.revealingletteremployeedetail')),
            ],
        ),
    ]
