# Generated by Django 5.0.6 on 2024-09-09 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitInterview', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='exitinterviewmaster',
            name='Experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExitInterview.experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exitrating',
            name='Rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExitInterview.rating'),
            preserve_default=False,
        ),
    ]
