# Generated by Django 5.0.6 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitInterview', '0002_experience_rating_reason_for_leaving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitinterviewdata',
            name='hotel',
            field=models.BigIntegerField(default=0),
        ),
    ]
