# Generated by Django 5.0.6 on 2024-10-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExitInterview', '0003_exitinterviewdata_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitinterviewdata',
            name='hotel',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
