# Generated by Django 4.1.7 on 2023-06-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesWeeklyReview', '0002_sourceentrymaster_sourcemaster_sourceentrydetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceentrydetails',
            old_name='RoomNights',
            new_name='RMNights',
        ),
    ]
