# Generated by Django 4.1.7 on 2023-06-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesWeeklyReview', '0004_otaentrymaster_otamaster_otaentrydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentrydetails',
            name='RPD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
