# Generated by Django 4.1.7 on 2023-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesWeeklyReview', '0007_companyproductivityentrymaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsegmententrymaster',
            name='TotalRevenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
