# Generated by Django 4.1.7 on 2023-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesWeeklyReview', '0008_marketsegmententrymaster_totalrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsegmententrymaster',
            name='TotalADR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
