# Generated by Django 4.1.7 on 2023-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesWeeklyReview', '0009_marketsegmententrymaster_totaladr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceentrymaster',
            name='TotalADR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sourceentrymaster',
            name='TotalRevenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
