# Generated by Django 4.1.7 on 2023-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesWeeklyReview', '0011_sourceentrymaster_totalrpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaentrymaster',
            name='TotalARR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='otaentrymaster',
            name='TotalRPD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='otaentrymaster',
            name='TotalRevenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
