# Generated by Django 5.0.6 on 2024-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeOfConduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplefile', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
