# Generated by Django 4.1.8 on 2023-08-24 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAssessmentEntryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainingDate', models.DateField(default=datetime.date.today)),
                ('EmpCode', models.CharField(blank=True, default='', max_length=200)),
                ('EmpName', models.CharField(blank=True, default='', max_length=200)),
                ('EmpDesignation', models.CharField(blank=True, default='', max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAssessmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAssessmentEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor'), ('Average', 'Average')], max_length=50)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('TrainingAssessmentEntryMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingAssessment.trainingassessmententrymaster')),
                ('TrainingAssessmentMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingAssessment.trainingassessmentmaster')),
            ],
        ),
    ]
