# Generated by Django 4.2.4 on 2023-09-18 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrEventCalendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hreventscalendar',
            },
        ),
        migrations.DeleteModel(
            name='HrEvent',
        ),
    ]
