# Generated by Django 4.2.4 on 2023-09-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrEvent', '0002_hreventcalendar_delete_hrevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hreventcalendar',
            name='end',
        ),
    ]
