# Generated by Django 4.1.8 on 2023-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrEvent', '0003_remove_hreventcalendar_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='hreventcalendar',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
