# Generated by Django 4.1.7 on 2023-03-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linen_Inventory_Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField()),
                ('To', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Linen_Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Title_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Linen_Item_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laundry', models.CharField(max_length=100)),
                ('Linen_Room', models.CharField(max_length=100)),
                ('Stores', models.CharField(max_length=100)),
                ('Missing', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
                ('Linen_Inventory_Sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlineninventory.linen_inventory_sheet')),
                ('Linen_Item_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlineninventory.linen_item_master')),
            ],
        ),
    ]
