# Generated by Django 4.1.7 on 2023-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlineninventory', '0002_linen_inventory_sheet_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linen_inventory_sheet',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
