# Generated by Django 5.0.2 on 2026-01-05 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlineninventory', '0003_linen_inventory_sheet_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linen_inventory_sheet',
            name='CreatedDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='linen_inventory_sheet',
            name='ModifyDateTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
