# Generated by Django 5.0.2 on 2025-01-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_detail_master',
            name='Salary_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.salarytitle_master'),
        ),
    ]
