# Generated by Django 5.0.2 on 2025-01-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_alter_salary_detail_master_salary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='NetProEmpID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
