# Generated by Django 5.0.11 on 2025-01-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_employeepersonaldetails_netproempid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='IsSecondary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
