# Generated by Django 5.0.11 on 2025-01-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_employeeworkdetails_issecondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonaldetails',
            name='NetProEmpID',
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='EmpID',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='EmployeeCode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
