# Generated by Django 5.0.11 on 2025-01-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_remove_employeepersonaldetails_netproempid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='WeekOffDay',
            field=models.CharField(blank=True, default='Sunday', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='EmpID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='EmployeeCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='OrganizationID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='EmpID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
