# Generated by Django 5.0.2 on 2025-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_employeeworkdetails_weekoffday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='InterviewAssessmentID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='Source',
            field=models.BigIntegerField(default=0),
        ),
    ]
