# Generated by Django 5.0.2 on 2025-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_alter_employeepersonaldetails_interviewassessmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='InterviewAssessmentID',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
