# Generated by Django 5.0.2 on 2025-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0009_alter_employeepersonaldetails_interviewassessmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='Division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkdetails',
            name='ReportingtoDivision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designationhistory',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='designationhistory',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='designationhistory',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeaddressinformationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeeaddressinformationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeeaddressinformationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeebankinformationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeebankinformationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeebankinformationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeechilddetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeechilddetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeedocumentsinformationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeedocumentsinformationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeedocumentsinformationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeemergencyinformationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeeemergencyinformationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeeemergencyinformationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeefamilydetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeefamilydetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeefamilydetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeidentityinformationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeeidentityinformationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeeidentityinformationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='EmpID',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='EmployeeCode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeepreviousworkinformationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeepreviousworkinformationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeepreviousworkinformationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeequalificationdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeequalificationdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeequalificationdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeurlmaster',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeeurlmaster',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeeworkdetails',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salary_detail_master',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salary_detail_master',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='salary_detail_master',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='EmpID',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salarytitle_master',
            name='IsDelete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='salarytitle_master',
            name='OrganizationID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
