# Generated by Django 5.0.2 on 2025-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0010_employeeworkdetails_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytitle_master',
            name='Calculation_Basis_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salarytitle_master',
            name='Category',
            field=models.CharField(blank=True, choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('CONTRIBUTION', 'Contribution'), ('TOTAL', 'Total')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarytitle_master',
            name='Display_Names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salarytitle_master',
            name='Formula_Expression',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salarytitle_master',
            name='Salary_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
