# Generated by Django 5.0.2 on 2025-08-21 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0011_salarytitle_master_calculation_basis_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PT_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('State', models.CharField(blank=True, max_length=255, null=True)),
                ('Hotel_ID', models.BigIntegerField(db_index=True, default=0)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Salary_From', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Salary_To', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PT_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Last_Month', models.IntegerField(blank=True, null=True)),
                ('Last_Month_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('IsActive', models.BooleanField(db_index=True, default=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
