# Generated by Django 5.0.2 on 2025-08-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0012_pt_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytitle_master',
            name='HotelID',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
