# Generated by Django 5.0.2 on 2025-10-02 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0013_salarytitle_master_hotelid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Details_Effective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.BigIntegerField(blank=True, default=0, null=True)),
                ('EffectiveFrom', models.DateTimeField()),
                ('CTC', models.CharField(blank=True, max_length=10, null=True)),
                ('OrganizationID', models.BigIntegerField(db_index=True, default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsDelete', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
