# Generated by Django 5.0.2 on 2025-10-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0014_salary_details_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_detail_master',
            name='Effective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.salary_details_effective'),
        ),
    ]
