# Generated by Django 5.0.2 on 2025-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0015_salary_detail_master_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_details_effective',
            name='EffectiveFrom',
            field=models.DateField(),
        ),
    ]
