# Generated by Django 5.0.2 on 2025-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0016_alter_salary_details_effective_effectivefrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='AccommodationFlatNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
