# Generated by Django 5.0.2 on 2025-11-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0017_employeeworkdetails_accommodationflatnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_detail_master',
            name='Salary_title_Old_Id',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
