# Generated by Django 5.0.2 on 2025-12-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0018_salary_detail_master_salary_title_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_details_effective',
            name='EffectiveTo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary_detail_master',
            name='Perannum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salary_detail_master',
            name='Permonth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary_details_effective',
            name='EffectiveFrom',
            field=models.DateField(blank=True, null=True),
        ),
    ]
